package newstart.fragments;

import android.content.Context;
import android.content.Intent;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.Bundle;
import android.os.Handler;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.AnimationUtils;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextSwitcher;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.content.ContextCompat;
import androidx.fragment.app.Fragment;

import newstart.R;
import newstart.activities.Activity_Calendar;
import newstart.activities.Activity_FullContent;
import newstart.data.DatabaseHelper;
import newstart.data.MealConstants;

import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayer;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.AbstractYouTubePlayerListener;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public class Fragment_Nutrition extends Fragment {

    private String date;
    private String todayBreakfast = "";
    private String todayLunch = "";
    private String todayDinner = "";

    private YouTubePlayer breakfastPlayer, lunchPlayer, dinnerPlayer;

    private TextSwitcher textSwitcherHints;
    private final int[] nutritionHints = {
            R.string.hint_nutr_1,
            R.string.hint_nutr_2,
            R.string.hint_nutr_3,
            R.string.hint_nutr_4,
            R.string.hint_nutr_5,
            R.string.hint_nutr_6
    };
    private int currentHintIdx = 0;
    private final Handler hintHandler = new Handler();
    private Runnable hintRunnable;

    private final String[][] mealSuggestionsPtJan = {
            {MealConstants.PT_AVEIA_MIRTILOS, MealConstants.PT_SALADA_QUINOA_LEGUMES, MealConstants.PT_BROCOLIS_TOFU_GRELHADO},
            {MealConstants.PT_PANQUECAS_INTEGRAIS, MealConstants.PT_TACOS_FEIJAO_MILHO, MealConstants.PT_SOPA_LENTILHA_COUVE},
            {MealConstants.PT_SMOOTHIE_LINHACA, MealConstants.PT_CARIL_GRAO_BICO, MealConstants.PT_SALADA_VERDE_SEMENTES},
            {MealConstants.PT_PAPA_SARRACENO, MealConstants.PT_WRAP_HUMUS, MealConstants.PT_SALTEADO_TEMPEH},
            {MealConstants.PT_PUDIM_CHIA, MealConstants.PT_CHILI_BATATA_DOCE, MealConstants.PT_COUVE_FLOR_TAHINI},
            {MealConstants.PT_TORRADA_ABACATE, MealConstants.PT_GISADO_LENTILHAS, MealConstants.PT_ZOODLES_PESTO},
            {MealConstants.PT_PAINCO_CAJU, MealConstants.PT_BOWL_QUINOA_FEIJAO, MealConstants.PT_BATATA_DOCE_FOLHAS_VERDES},
            {MealConstants.PT_MEXIDO_TOFU_ESPINAFRES, MealConstants.PT_SALADA_FARRO, MealConstants.PT_RAIZES_ASSADAS_ALHO},
            {MealConstants.PT_TACA_ACAI, MealConstants.PT_MASSA_LENTILHA_MARINARA, MealConstants.PT_SALADA_COUVE_QUINOA},
            {MealConstants.PT_QUINOA_PEQUENO_ALMOCO, MealConstants.PT_EMPADAO_LENTILHA, MealConstants.PT_ESPARGOS_ASSADOS},
            {MealConstants.PT_TORRADA_AMENDOIM_BANANA, MealConstants.PT_BOWL_BUDDHA_GRAO, MealConstants.PT_PIMENTOS_RECHEADOS},
            {MealConstants.PT_SMOOTHIE_BOWL_FRUTOS_SECOS, MealConstants.PT_SOPA_CEVADA_VEGETAIS, MealConstants.PT_RISOTO_COGUMELOS},
            {MealConstants.PT_PAPAS_MILHO, MealConstants.PT_WRAP_FALAFEL, MealConstants.PT_LASANHA_BERINGELA},
            {MealConstants.PT_AVEIA_MACA_CANELA, MealConstants.PT_SOPA_ERVILHA, MealConstants.PT_TOFU_AGRIDOCE},
            {MealConstants.PT_BURRITO_VEG, MealConstants.PT_TABULE_SALSA, MealConstants.PT_COUVE_BRUXELAS_BALSAMICO},
            {MealConstants.PT_GRANOLA_LEITE_AMENDOAS, MealConstants.PT_SOPA_MINESTRONE, MealConstants.PT_BOK_CHOY_TEMPEH},
            {MealConstants.PT_ABOCATE_CENTEIO, MealConstants.PT_SALADA_FEIJAO_FRADE, MealConstants.PT_ABOBORA_ASSADA_QUINOA},
            {MealConstants.PT_MUESLI_FRUTAS, MealConstants.PT_PAELLA_VEGETAIS, MealConstants.PT_BIFES_PORTOBELLO},
            {MealConstants.PT_QUINOA_PESSEGOS, MealConstants.PT_SOPA_REPOLHO_BATATAS, MealConstants.PT_BIFES_COUVE_FLOR},
            {MealConstants.PT_PANQUECAS_BANANA, MealConstants.PT_SALADA_GRAO_MEDITERRANEA, MealConstants.PT_SALTEADO_BROCOLIS_CAJU},
            {MealConstants.PT_AVEIA_ABOBORA, MealConstants.PT_KORMA_VEGETAIS, MealConstants.PT_BETERRABA_GLACIADA},
            {MealConstants.PT_IOGURTE_SOJA_FRUTAS, MealConstants.PT_SOPA_FEIJAO_BRANCO, MealConstants.PT_SALADA_REPOLHO_CENOURA},
            {MealConstants.PT_PAO_ESPELTA_MANTEIGA, MealConstants.PT_LENTILHA_ARROZ_MUJADARA, MealConstants.PT_ALCACHOFRAS_VAPOR},
            {MealConstants.PT_MEXIDO_TOFU_VEGETAIS, MealConstants.PT_SALADA_GRAO_ASSADO, MealConstants.PT_PALITOS_BATATA_DOCE},
            {MealConstants.PT_PAPAS_PERA_NOZ, MealConstants.PT_CHILI_TRES_FEIJOES, MealConstants.PT_VAGEM_ALHO},
            {MealConstants.PT_SMOOTHIE_ESPINAFRES, MealConstants.PT_SUSHI_VEGGIE, MealConstants.PT_SOPA_MISO_TOFU},
            {MealConstants.PT_SARRACENO_ERVAS, MealConstants.PT_GISADO_TOMATE_LENTILHAS, MealConstants.PT_ERVILHAS_QUEBRAR_SALTEADAS},
            {MealConstants.PT_SALADA_FRUTA_CANHAMO, MealConstants.PT_QUINOA_ROMA, MealConstants.PT_SALTEADO_ABOBORINHA_MILHO},
            {MealConstants.PT_TORRADA_HUMUS, MealConstants.PT_SOPA_CEVADA_COGUMELOS, MealConstants.PT_VEGETAIS_VAPOR},
            {MealConstants.PT_PARFAIT_VEGAN, MealConstants.PT_TOFU_BROCOLIS_AMENDOIM, MealConstants.PT_ABOBORA_MENINA_ASSADA},
            {MealConstants.PT_AVEIA_FIGOS, MealConstants.PT_BOWL_QUINOA_MEXICANO, MealConstants.PT_ACELGA_ALHO}
    };

    private final String[][] mealSuggestionsPtFeb = {
            {MealConstants.PT_FEB_SMOOTHIE_MANGA, MealConstants.PT_FEB_SALADA_GRAO_ESPINAFRES, MealConstants.PT_FEB_SOPA_VERDE},
            {MealConstants.PT_FEB_AVEIA_AMENDOA, MealConstants.PT_FEB_RISOTO_ABOBORA, MealConstants.PT_FEB_OMELETE_ESPINAFRES},
            {MealConstants.PT_FEB_PANQUECAS_MIRTILO, MealConstants.PT_FEB_MASSA_PESTO_TOMATE, MealConstants.PT_FEB_SALADA_TROPICAL},
            {MealConstants.PT_FEB_PUDIM_CHIA_MORANGO, MealConstants.PT_FEB_ESTUFADO_FEIJAO_BRANCO, MealConstants.PT_FEB_TOFU_GRELHADO_SALADA},
            {MealConstants.PT_FEB_TORRADA_RICOTA, MealConstants.PT_FEB_HAMBURGUER_LENTILHAS, MealConstants.PT_FEB_SOPA_CENOURA_LARANJA},
            {MealConstants.PT_FEB_SMOOTHIE_VERDE, MealConstants.PT_FEB_CARIL_VEGETAIS_COCO, MealConstants.PT_FEB_SANDES_VEG_HUMUS},
            {MealConstants.PT_FEB_TACA_IOGURTE, MealConstants.PT_FEB_QUINOA_COGUMELOS, MealConstants.PT_FEB_OVOS_ESCALFADOS_TOMATE},
            {MealConstants.PT_FEB_MEXIDO_TOFU_COGUMELOS, MealConstants.PT_FEB_SOPA_ABOBORA_GENGIBRE, MealConstants.PT_FEB_CREME_ERVILHAS},
            {MealConstants.PT_FEB_PAPAS_AVELA, MealConstants.PT_FEB_SALADA_LENTILHAS_FETA, MealConstants.PT_FEB_TOFU_MARINADO_LEGUMES},
            {MealConstants.PT_FEB_SMOOTHIE_BANANA_CACAU, MealConstants.PT_FEB_LASANHA_VEGETARIANA, MealConstants.PT_FEB_MINIESTRONE_LEVE},
            {MealConstants.PT_FEB_TORRADA_ABACATE_OVO, MealConstants.PT_FEB_ARROZ_ERVAS_TOFU, MealConstants.PT_FEB_SALADA_QUINOA_SIMPLES},
            {MealConstants.PT_FEB_GRANOLA_IOGURTE_MEL, MealConstants.PT_FEB_FEIJOADA_VEG, MealConstants.PT_FEB_COGUMELOS_SALTEADOS_ERVAS},
            {MealConstants.PT_FEB_PAPA_QUINOA_COCO, MealConstants.PT_FEB_GRATINADO_LEGUMES, MealConstants.PT_FEB_SOPA_FEIJAO_VERDE},
            {MealConstants.PT_FEB_AVEIA_AMORA, MealConstants.PT_FEB_SALADA_MACARRAO_VEG, MealConstants.PT_FEB_TOFU_SALTEADO_PIMENTOS},
            {MealConstants.PT_FEB_PANQUECAS_AVEIA_CANELA, MealConstants.PT_FEB_STROGONOFF_COGUMELOS, MealConstants.PT_FEB_SALADA_MACARRAO_FRIO},
            {MealConstants.PT_FEB_SMOOTHIE_PITAYA, MealConstants.PT_FEB_WRAP_FALAFEL_SALADA, MealConstants.PT_FEB_SOPA_CEBOLA_GRATINADA},
            {MealConstants.PT_FEB_TORRADA_TOMATE_ALHO, MealConstants.PT_FEB_SOPA_LENTILHAS_VERMELHAS, MealConstants.PT_FEB_TABULE_SIMPLES},
            {MealConstants.PT_FEB_MUESLI_IOGURTE, MealConstants.PT_FEB_BATATA_RECHEADA_VEG, MealConstants.PT_FEB_COUVE_FLOR_GRELHADA},
            {MealConstants.PT_FEB_AVEIA_PERA_CANELA, MealConstants.PT_FEB_SALADA_QUINOA_MANGA, MealConstants.PT_FEB_SOPA_GRAO_ESPINAFRES},
            {MealConstants.PT_FEB_SMOOTHIE_LARANJA_CENOURA, MealConstants.PT_FEB_PAELLA_COGUMELOS, MealConstants.PT_FEB_WRAP_TOFU_LEGUMES},
            {MealConstants.PT_FEB_PUDIM_CHIA_CHOCOLATE, MealConstants.PT_FEB_COUSCOUS_LEGUMES, MealConstants.PT_FEB_SALADA_AVOCADO_TOMATE},
            {MealConstants.PT_FEB_TORRADA_MANTEIGA_AVELA, MealConstants.PT_FEB_BOLINHOS_GRAO, MealConstants.PT_FEB_SOPA_BATATA_ALHO_FRANCES},
            {MealConstants.PT_FEB_MEXIDO_LEGUMES, MealConstants.PT_FEB_SOPA_TOMATE_OVO, MealConstants.PT_FEB_OVO_COZIDO_SALADA},
            {MealConstants.PT_FEB_PAPAS_TRIGO_SARRACENO, MealConstants.PT_FEB_SALTEADO_TOFU_BROCOLOS, MealConstants.PT_FEB_TOFU_ASSADO_ESPECIARIAS},
            {MealConstants.PT_FEB_SMOOTHIE_BOWL_MANGA, MealConstants.PT_FEB_RISOTO_COGUMELOS_TRUFA, MealConstants.PT_FEB_SOPA_TOMATE_MANJERICO},
            {MealConstants.PT_FEB_AVEIA_COCO_ANANAS, MealConstants.PT_FEB_ESTUFADO_LEGUMES_LENTILHAS, MealConstants.PT_FEB_ESTUFADO_GRAO_SIMPLES},
            {MealConstants.PT_FEB_PANQUECAS_ABOBORA, MealConstants.PT_FEB_SALADA_BETERRABA_NOZ, MealConstants.PT_FEB_SALADA_FETA_AZEITONAS},
            {MealConstants.PT_FEB_TORRADA_QUEIJO_MEL, MealConstants.PT_FEB_QUICHE_ESPINAFRES, MealConstants.PT_FEB_SOPA_LEGUMES_VARIADOS},
            {MealConstants.PT_FEB_SMOOTHIE_FRAMBOESA, MealConstants.PT_FEB_MASSA_ALHO_OLEO_VEG, MealConstants.PT_FEB_TOFU_MEXIDO_SIMPLES}
    };

    private final String[][] mealSuggestionsPtMar = {
            {MealConstants.PT_MAR_SMOOTHIE_KIWI, MealConstants.PT_MAR_CARIL_LENTILHAS, MealConstants.PT_MAR_SOPA_ALFACE_ERVILHAS},
            {MealConstants.PT_MAR_AVEIA_BANANA, MealConstants.PT_MAR_SALADA_QUINOA_BROCOLOS, MealConstants.PT_MAR_TOFU_GRELHADO_LEGUMES},
            {MealConstants.PT_MAR_TORRADA_ABACATE_SESAMO, MealConstants.PT_MAR_MASSA_COGUMELOS_SOJA, MealConstants.PT_MAR_SALADA_TOMATE_PEPINO},
            {MealConstants.PT_MAR_IOGURTE_GRANOLA_MACA, MealConstants.PT_MAR_CHILI_FEIJAO_MILHO, MealConstants.PT_MAR_CREME_CENOURA_COENTROS},
            {MealConstants.PT_MAR_PANQUECAS_MACA, MealConstants.PT_MAR_ALMONDEGAS_LENTILHA, MealConstants.PT_MAR_COGUMELOS_SALTEADOS_ALHO},
            {MealConstants.PT_MAR_SMOOTHIE_BOWL_VERMELHOS, MealConstants.PT_MAR_RISOTO_ESPARGOS_ERVILHAS, MealConstants.PT_MAR_SOPA_FEIJAO_VERDE_MASSA},
            {MealConstants.PT_MAR_PUDIM_CHIA_FRAMBOESA, MealConstants.PT_MAR_ESTUFADO_GRAO_COUVE, MealConstants.PT_MAR_CREME_BROCOLOS},
            {MealConstants.PT_MAR_TORRADA_AMENDOIM_MACA, MealConstants.PT_MAR_HAMBURGUER_GRAO_SALADA, MealConstants.PT_MAR_SALADA_RUSSA_VEG},
            {MealConstants.PT_MAR_OMELETE_TOFU_TOMATE, MealConstants.PT_MAR_COUSCOUS_MEDITERRANEO, MealConstants.PT_MAR_SOPA_LEGUMES_VARIADOS},
            {MealConstants.PT_MAR_PAPAS_MILHO_CANELA, MealConstants.PT_MAR_LASANHA_ESPINAFRES, MealConstants.PT_MAR_OMELETE_ERVAS_SALADA},
            {MealConstants.PT_MAR_SMOOTHIE_MANGA_LARANJA, MealConstants.PT_MAR_SALADA_MACARRAO_PESTO, MealConstants.PT_MAR_CREME_ABOBORA_SEMENTES},
            {MealConstants.PT_MAR_TACA_ACAI_COCO, MealConstants.PT_MAR_ARROZ_FEIJAO_LEGUMES, MealConstants.PT_MAR_GASPACHO_TOMATE},
            {MealConstants.PT_MAR_TORRADA_HUMUS_PEPINO, MealConstants.PT_MAR_TORTILHA_BATATA_CEBOLA, MealConstants.PT_MAR_SOPA_LENTILHAS_ESPINAFRES},
            {MealConstants.PT_MAR_MUESLI_PASSAS, MealConstants.PT_MAR_QUICHE_COGUMELOS_ALHO, MealConstants.PT_MAR_SALADA_GREGA_FETA},
            {MealConstants.PT_MAR_QUINOA_AMENDOAS, MealConstants.PT_MAR_SALADA_LENTILHAS_ROMA, MealConstants.PT_MAR_CREME_COUVE_FLOR},
            {MealConstants.PT_MAR_SMOOTHIE_MORANGO_BANANA, MealConstants.PT_MAR_MASSA_TOMATE_MANJERICO, MealConstants.PT_MAR_TOFU_SOJA_GENGIBRE},
            {MealConstants.PT_MAR_PANQUECAS_INTEGRAIS_MEL, MealConstants.PT_MAR_GRATINADO_COUVE_FLOR, MealConstants.PT_MAR_SOPA_GRAO_MASSA},
            {MealConstants.PT_MAR_PAPAS_SARRACENO_PERA, MealConstants.PT_MAR_EMPADAO_SOJA, MealConstants.PT_MAR_SALADA_ESPINAFRES_MACA},
            {MealConstants.PT_MAR_TORRADA_REQUEIJAO_DOCE, MealConstants.PT_MAR_SALADA_FEIJAO_FRADE_PIMENTO, MealConstants.PT_MAR_CREME_ERVILHAS_HORTELA},
            {MealConstants.PT_MAR_IOGURTE_GOJI, MealConstants.PT_MAR_TOFU_BROAS_GRELOS, MealConstants.PT_MAR_OVOS_TOMATE_SHAKSHUKA},
            {MealConstants.PT_MAR_SMOOTHIE_ANANAS_HORTELA, MealConstants.PT_MAR_RISOTO_COGUMELOS_SELVAGENS, MealConstants.PT_MAR_SOPA_MINESTRONE_MAR},
            {MealConstants.PT_MAR_TAPIOCA_BANANA, MealConstants.PT_MAR_CARIL_VEGETAIS_GRAO, MealConstants.PT_MAR_SALADA_BETERRABA_LARANJA},
            {MealConstants.PT_MAR_AVEIA_CHOCOLATE, MealConstants.PT_MAR_CANELONES_ESPINAFRES_TOFU, MealConstants.PT_MAR_CREME_COURGETTE},
            {MealConstants.PT_MAR_SMOOTHIE_BOWL_SPIRULINA, MealConstants.PT_MAR_SALADA_GRAO_BETERRABA, MealConstants.PT_MAR_PORTOBELLO_GRELHADO_SALADA},
            {MealConstants.PT_MAR_TORRADA_ABACATE_CHERRY, MealConstants.PT_MAR_MASSA_ABOBORA_SALVIA, MealConstants.PT_MAR_SOPA_TOMATE_MANJERICO},
            {MealConstants.PT_MAR_MUFFIN_MIRTILO, MealConstants.PT_MAR_HAMBURGUER_FEIJAO_ARROZ, MealConstants.PT_MAR_SALADA_ALFACE_MILHO},
            {MealConstants.PT_MAR_SMOOTHIE_PAPAIA_LIMA, MealConstants.PT_MAR_ESTUFADO_LENTILHAS_CENOURA, MealConstants.PT_MAR_CREME_ESPARGOS},
            {MealConstants.PT_MAR_PAPAS_ARROZ_COCO, MealConstants.PT_MAR_SALADA_MASSA_TOFU, MealConstants.PT_MAR_TOFU_MEXIDO_ESPINAFRES},
            {MealConstants.PT_MAR_TORRADA_MANTEIGA_AMENDOA, MealConstants.PT_MAR_ARROZ_TOMATE_OVOS, MealConstants.PT_MAR_SOPA_CEBOLA},
            {MealConstants.PT_MAR_TACA_IOGURTE_GIRASSOL, MealConstants.PT_MAR_QUINOA_TOFU_AMENDOAS, MealConstants.PT_MAR_SALADA_GRAO_COUVE_FLOR},
            {MealConstants.PT_MAR_SMOOTHIE_MELAO_GENGIBRE, MealConstants.PT_MAR_PAELLA_VEGETAIS_MAR, MealConstants.PT_MAR_CREME_LEGUMES_CROUTONS}
    };

    private final String[][] mealSuggestionsPtApr = {
            {MealConstants.PT_APR_SMOOTHIE_MORANGO_CHIA, MealConstants.PT_APR_RISOTO_ESPARGOS, MealConstants.PT_APR_SOPA_ALFACE_HORTELA},
            {MealConstants.PT_APR_AVEIA_AMENDOA_MEL, MealConstants.PT_APR_SALADA_QUINOA_GRAO, MealConstants.PT_APR_TOFU_GRELHADO_VERDE},
            {MealConstants.PT_APR_TORRADA_ABACATE_OVO, MealConstants.PT_APR_MASSA_PESTO_PINHOES, MealConstants.PT_APR_SALADA_CAPRESE},
            {MealConstants.PT_APR_IOGURTE_GRANOLA_TROPICAL, MealConstants.PT_APR_CHILI_LENTILHAS_DOCE, MealConstants.PT_APR_CREME_CENOURA_GENGIBRE},
            {MealConstants.PT_APR_PANQUECAS_ESPELTA, MealConstants.PT_APR_ALMONDEGAS_BERINJELA, MealConstants.PT_APR_COGUMELOS_SALTEADOS},
            {MealConstants.PT_APR_SMOOTHIE_BOWL_SPIRULINA, MealConstants.PT_APR_TORTA_ESPINAFRES, MealConstants.PT_APR_SOPA_FEIJAO_VERDE},
            {MealConstants.PT_APR_PUDIM_CHIA_KIWI, MealConstants.PT_APR_ESTUFADO_FEIJAO_BRANCO, MealConstants.PT_APR_CREME_BROCOLOS_QUEIJO},
            {MealConstants.PT_APR_TORRADA_AMENDOIM_MIRTILO, MealConstants.PT_APR_HAMBURGUER_GRAO_BATATA, MealConstants.PT_APR_SALADA_RUSSA_VEG},
            {MealConstants.PT_APR_MEXIDO_TOFU_TOMATE, MealConstants.PT_APR_COUSCOUS_LEGUMES, MealConstants.PT_APR_SOPA_LEGUMES_EPOCA},
            {MealConstants.PT_APR_PAPAS_MILHO_COCO, MealConstants.PT_APR_LASANHA_ABOBORINHA, MealConstants.PT_APR_OMELETE_ESPINAFRES},
            {MealConstants.PT_APR_SMOOTHIE_BANANA_ESPINAFRE, MealConstants.PT_APR_SALADA_MACARRAO_TOMATE, MealConstants.PT_APR_CREME_ABOBORA_SEMENTES},
            {MealConstants.PT_APR_TACA_ACAI_CANHAMO, MealConstants.PT_APR_ARROZ_FEIJAO_VAPOR, MealConstants.PT_APR_GASPACHO_MORANGO},
            {MealConstants.PT_APR_TORRADA_HUMUS_PIMENTOS, MealConstants.PT_APR_TORTILHA_BATATA_ALHO, MealConstants.PT_APR_SOPA_LENTILHAS_VERMELHAS},
            {MealConstants.PT_APR_MUESLI_AVELA, MealConstants.PT_APR_QUICHE_LEGUMES, MealConstants.PT_APR_SALADA_GREGA_PEPINO},
            {MealConstants.PT_APR_QUINOA_MACA, MealConstants.PT_APR_SALADA_LENTILHAS_MACA, MealConstants.PT_APR_CREME_COUVE_FLOR},
            {MealConstants.PT_APR_SMOOTHIE_MANGA_HORTELA, MealConstants.PT_APR_MASSA_TOMATE_AZEITONAS, MealConstants.PT_APR_TOFU_LIMAO},
            {MealConstants.PT_APR_PANQUECAS_BANANA_NOZ, MealConstants.PT_APR_GRATINADO_COUVE_FLOR, MealConstants.PT_APR_SOPA_GRAO_ESPINAFRES},
            {MealConstants.PT_APR_PAPAS_SARRACENO_MORANGO, MealConstants.PT_APR_EMPADAO_LENTILHAS, MealConstants.PT_APR_SALADA_RUCULA_PERA},
            {MealConstants.PT_APR_TORRADA_QUEIJO_MEL, MealConstants.PT_APR_SALADA_FEIJAO_FRADE, MealConstants.PT_APR_CREME_ERVILHAS},
            {MealConstants.PT_APR_IOGURTE_LINHACA_PAPAIA, MealConstants.PT_APR_TOFU_ERVAS_ARROZ, MealConstants.PT_APR_OVOS_TOMATE_SHAKSHUKA},
            {MealConstants.PT_APR_SMOOTHIE_SILVESTRES, MealConstants.PT_APR_RISOTO_ABOBORA_SALVIA, MealConstants.PT_APR_SOPA_MINESTRONE_LEVE},
            {MealConstants.PT_APR_TAPIOCA_QUEIJO_TOMATE, MealConstants.PT_APR_CARIL_GRAO_ESPINAFRES, MealConstants.PT_APR_SALADA_BETERRABA_LARANJA},
            {MealConstants.PT_APR_AVEIA_TAMARAS, MealConstants.PT_APR_CANELONES_TOFU, MealConstants.PT_APR_CREME_COURGETTE_MANJERICO},
            {MealConstants.PT_APR_SMOOTHIE_BOWL_ABACATE, MealConstants.PT_APR_SALADA_QUINOA_MANGA, MealConstants.PT_APR_PORTOBELLO_GRELHADO},
            {MealConstants.PT_APR_TORRADA_COGUMELOS, MealConstants.PT_APR_MASSA_BROCOLOS_ALHO, MealConstants.PT_APR_SOPA_TOMATE_ARROZ},
            {MealConstants.PT_APR_MUFFIN_AVEIA_MACA, MealConstants.PT_APR_HAMBURGUER_LENTILHAS_SALADA, MealConstants.PT_APR_SALADA_ALFACE_MILHO_ABACATE},
            {MealConstants.PT_APR_SMOOTHIE_PERA_CANELA, MealConstants.PT_APR_ESTUFADO_ERVILHAS_OVOS, MealConstants.PT_APR_CREME_ESPARGOS_VERDES},
            {MealConstants.PT_APR_PAPAS_CEVADA_MEL, MealConstants.PT_APR_SALADA_MACARRAO_MILHO, MealConstants.PT_APR_TOFU_MEXIDO_ERVAS},
            {MealConstants.PT_APR_TORRADA_CAJU_BANANA, MealConstants.PT_APR_ARROZ_TOMATE_TOFU, MealConstants.PT_APR_SOPA_CEBOLA},
            {MealConstants.PT_APR_TACA_IOGURTE_ABOBORA, MealConstants.PT_APR_QUINOA_LEGUMES_TAHINI, MealConstants.PT_APR_SALADA_GRAO_CHERRY}
    };

    private final String[][] mealSuggestionsPtMay = {
            {MealConstants.PT_MAY_SMOOTHIE_ANANAS_COCO, MealConstants.PT_MAY_CARIL_GRAO_ESPINAFRES, MealConstants.PT_MAY_SOPA_ALFACE_HORTELA_LEVE},
            {MealConstants.PT_MAY_AVEIA_MORANGO, MealConstants.PT_MAY_SALADA_QUINOA_TROPICAL, MealConstants.PT_MAY_TOFU_GRELHADO_SALADA_VERDE},
            {MealConstants.PT_MAY_TORRADA_ABACATE_RABANETE, MealConstants.PT_MAY_MASSA_PRIMAVERA, MealConstants.PT_MAY_GASPACHO_TOMATE_PEPINO},
            {MealConstants.PT_MAY_PUDIM_CHIA_ANANAS, MealConstants.PT_MAY_CHILI_VEGETARIANO_LEVE, MealConstants.PT_MAY_SALADA_TOMATE_MOZZARELLA_BASILICO},
            {MealConstants.PT_MAY_PANQUECAS_MIRTILO_LIMAO, MealConstants.PT_MAY_RISOTO_COGUMELOS_ERVAS, MealConstants.PT_MAY_CREME_CENOURA_GENGIBRE_LEVE},
            {MealConstants.PT_MAY_SMOOTHIE_BOWL_VERDE, MealConstants.PT_MAY_SALADA_LENTILHAS_FETA, MealConstants.PT_MAY_COGUMELOS_SALTEADOS_ERVAS_FRESCAS},
            {MealConstants.PT_MAY_TACA_IOGURTE_KIWI, MealConstants.PT_MAY_TORTILHA_ESPINAFRES_COGUMELOS, MealConstants.PT_MAY_SOPA_FEIJAO_VERDE_MASSA_LEVE},
            {MealConstants.PT_MAY_TORRADA_MANTEIGA_AMENDOIM_MORANGO, MealConstants.PT_MAY_ARROZ_ERVAS_TOFU_GRELHADO, MealConstants.PT_MAY_SALADA_RUCULA_MORANGO_FETA},
            {MealConstants.PT_MAY_MEXIDO_TOFU_TOMATE_CHERRY, MealConstants.PT_MAY_SALADA_GRAO_PIMENTOS, MealConstants.PT_MAY_CREME_BROCOLOS_LEVE},
            {MealConstants.PT_MAY_AVEIA_COCO_MANGA, MealConstants.PT_MAY_COUSCOUS_VEGETAIS_GRELHADOS, MealConstants.PT_MAY_OMELETE_ESPINAFRES_QUEIJO},
            {MealConstants.PT_MAY_SMOOTHIE_FRAMBOESA_BANANA, MealConstants.PT_MAY_LASANHA_VEGETAL_LEVE, MealConstants.PT_MAY_SOPA_LEGUMES_DA_HORTA},
            {MealConstants.PT_MAY_PANQUECAS_AVEIA_MEL, MealConstants.PT_MAY_SALADA_MACARRAO_TOMATE_BASILICO, MealConstants.PT_MAY_SALADA_RUSSA_VEGETARIANA},
            {MealConstants.PT_MAY_TORRADA_HUMUS_TOMATE, MealConstants.PT_MAY_ESTUFADO_LENTILHAS_VERMELHAS, MealConstants.PT_MAY_CREME_ABOBORA_SEMENTES_GIRASSOL},
            {MealConstants.PT_MAY_MUESLI_FRUTOS_VERMELHOS, MealConstants.PT_MAY_HAMBURGUER_FEIJAO_SALADA, MealConstants.PT_MAY_TOFU_MEXIDO_LEGUMES},
            {MealConstants.PT_MAY_PAPA_QUINOA_MACA, MealConstants.PT_MAY_SALADA_QUINOA_AVOCADO, MealConstants.PT_MAY_SOPA_LENTILHAS_VERMELHAS_COENTROS},
            {MealConstants.PT_MAY_SMOOTHIE_MANGA_LIMA, MealConstants.PT_MAY_ARROZ_TOMATE_PANADOS_VEG, MealConstants.PT_MAY_SALADA_GREGA_SIMPLES},
            {MealConstants.PT_MAY_TORRADA_ABACATE_OVO_ESCALFADO, MealConstants.PT_MAY_QUICHE_ALHO_FRANCES_COGUMELOS, MealConstants.PT_MAY_CREME_COUVE_FLOR_ALHO_FRANCES},
            {MealConstants.PT_MAY_TACA_ACAI_GRANOLA, MealConstants.PT_MAY_SALADA_FEIJAO_FRADE_ATUM_VEG, MealConstants.PT_MAY_WRAP_TOFU_SALADA},
            {MealConstants.PT_MAY_PAPAS_MILHO_DOCE, MealConstants.PT_MAY_MASSA_PESTO_TOMATE_CHERRY, MealConstants.PT_MAY_SOPA_GRAO_ESPINAFRES_LEVE},
            {MealConstants.PT_MAY_SMOOTHIE_BOWL_MORANGO, MealConstants.PT_MAY_GRATINADO_LEGUMES_PRIMAVERA, MealConstants.PT_MAY_SALADA_ESPINAFRE_MACA_NOZ},
            {MealConstants.PT_MAY_AVEIA_ANANAS_HORTELA, MealConstants.PT_MAY_SALADA_LENTILHAS_MACA_NOZ, MealConstants.PT_MAY_CREME_ERVILHAS_HORTELA_FRESCA},
            {MealConstants.PT_MAY_PANQUECAS_BANANA_CANELA, MealConstants.PT_MAY_RISOTO_ABOBORA_NOZ_MOSCADA, MealConstants.PT_MAY_OVOS_ESTRELADOS_TOMATE},
            {MealConstants.PT_MAY_TORRADA_QUEIJO_FRESCO_TOMATE, MealConstants.PT_MAY_CANELONES_RICOTA_ESPINAFRES, MealConstants.PT_MAY_SOPA_MINESTRONE_LEVE},
            {MealConstants.PT_MAY_IOGURTE_GRANOLA_MIRTILO, MealConstants.PT_MAY_SALADA_QUINOA_MANGA_AMENDOA, MealConstants.PT_MAY_SALADA_BETERRABA_LARANJA_NOZ},
            {MealConstants.PT_MAY_SMOOTHIE_ESPINAFRE_MACA, MealConstants.PT_MAY_CARIL_VEGETAIS_COCO_LEVE, MealConstants.PT_MAY_CREME_COURGETTE_COENTROS},
            {MealConstants.PT_MAY_PUDIM_CHIA_MANGA_COCO, MealConstants.PT_MAY_SALTEADO_TOFU_LEGUMES_CROCANTES, MealConstants.PT_MAY_PORTOBELLO_GRELHADO_ERVAS},
            {MealConstants.PT_MAY_TORRADA_ABACATE_PIMENTAO, MealConstants.PT_MAY_SOPA_TOMATE_OVO_ESCALFADO, MealConstants.PT_MAY_SOPA_TOMATE_ARROZ_LEVE},
            {MealConstants.PT_MAY_AVEIA_CHOCOLATE_MORANGO, MealConstants.PT_MAY_SALADA_MACARRAO_PESTO_RUCULA, MealConstants.PT_MAY_SALADA_ALFACE_MILHO_ABACATE},
            {MealConstants.PT_MAY_SMOOTHIE_SILVESTRE_LINHACA, MealConstants.PT_MAY_EMPADAO_VEGETARIANO_LENTILHAS, MealConstants.PT_MAY_CREME_ESPARGOS_VERDES_LEVE},
            {MealConstants.PT_MAY_PANQUECAS_INTEGRAIS_FRUTA, MealConstants.PT_MAY_PAELLA_VEGETARIANA_PRIMAVERA, MealConstants.PT_MAY_TOFU_SALTEADO_SOJA_GENGIBRE},
            {MealConstants.PT_MAY_TACA_IOGURTE_MEL_NOZES, MealConstants.PT_MAY_SALADA_GRAO_MEDITERRANICA, MealConstants.PT_MAY_SOPA_CEBOLA_LEVE}
    };

    private final String[][] mealSuggestionsPtJun = {
            {MealConstants.PT_JUN_WAFFLE_TRIGO_SARRACENO, MealConstants.PT_JUN_FALAFEL_FORNO_MOLHO_TAHINI, MealConstants.PT_JUN_CALDO_VERDE_TRADICIONAL_VEG},
            {MealConstants.PT_JUN_PANQUECA_ESPINAFRE_COGUMELO, MealConstants.PT_JUN_CHILI_VEGANO_SIN_CARNE, MealConstants.PT_JUN_SOPA_CREME_ALHO_FRANCES_BATATA},
            {MealConstants.PT_JUN_BATIDO_CELESTE_SPIRULINA, MealConstants.PT_JUN_ESPARGUETE_CURGETE_PESTO_AVELA, MealConstants.PT_JUN_CANJA_COGUMELOS_SHIITAKE_MASSA},
            {MealConstants.PT_JUN_CREME_AVEIA_FORNO_NOZES, MealConstants.PT_JUN_FEIJOADA_COGUMELOS_PLEUROTUS, MealConstants.PT_JUN_SOPA_FEIJAO_MANTEIGA_REPOLHO},
            {MealConstants.PT_JUN_TORRADA_TAPENADE_TOMATE, MealConstants.PT_JUN_ESTUFADO_LENTILHAS_ABOBORA_MANTEIGA, MealConstants.PT_JUN_CREME_BROCOLOS_AMENDOA_TOSTADA},
            {MealConstants.PT_JUN_GRANOLA_SALGADA_IOGURTE, MealConstants.PT_JUN_STIR_FRY_TOFU_BROCOLOS_SESAMO, MealConstants.PT_JUN_SOPA_TOMATE_ALENTEJANA_OVO},
            {MealConstants.PT_JUN_SUMO_PRENSADO_CENOURA_TURMERIC, MealConstants.PT_JUN_ALHO_FRANCES_RECHEADO_QUINOA, MealConstants.PT_JUN_CREME_ERVIHAS_XUXU_ERVAS},
            {MealConstants.PT_JUN_MACA_ASSADA_RECHEADA_CHIA, MealConstants.PT_JUN_SALADA_QUENTE_BATATA_DOCE_LENTILHAS, MealConstants.PT_JUN_SOPA_MINESTRONE_FEIJAO_FRADE},
            {MealConstants.PT_JUN_PUDIM_LINHACA_LEITE_AVELA, MealConstants.PT_JUN_MASSA_ORZO_TOMATE_FORNO, MealConstants.PT_JUN_CREME_ABOBORA_ASSADA_GENGIBRE},
            {MealConstants.PT_JUN_GALETTE_FRANQUESA_MORANGO, MealConstants.PT_JUN_CURRY_RAMEN_TOFU_FRESCO, MealConstants.PT_JUN_SOPA_PEDRA_VEGETARIANA_RIFADO},
            {MealConstants.PT_JUN_SCOTTISH_OATS_SALGADAS, MealConstants.PT_JUN_GNOCCHI_ABOBORA_SALVIA_AZEITE, MealConstants.PT_JUN_CREME_CENOURA_SOUCHE_COENTROS},
            {MealConstants.PT_JUN_MUFFIN_AVEIA_CENOURA_NOZ, MealConstants.PT_JUN_XAREM_ALGARVIO_COGUMELOS, MealConstants.PT_JUN_SOPA_LENTILHAS_VERMELHAS_COMINHO},
            {MealConstants.PT_JUN_TORRADA_RICOTA_RABANETE_ASSADO, MealConstants.PT_JUN_BURRITO_BOWL_ARROZ_FEIJAO_PRETO, MealConstants.PT_JUN_CREME_COUVE_FLOR_ALHO_ASSADO},
            {MealConstants.PT_JUN_BATIDO_PROTEICO_ERVIHA_CACAU, MealConstants.PT_JUN_LASANHA_LENTILHAS_FOLHAS_COUVE, MealConstants.PT_JUN_SOPA_JULIANA_LEGUMES_VARIADOS},
            {MealConstants.PT_JUN_CREPE_AVEIA_COMPOTA_ABOBORA, MealConstants.PT_JUN_COUSCOUS_ISRAELITA_VEGETAIS_FORNO, MealConstants.PT_JUN_CREME_XUXU_FOLHAS_NABICA},
            {MealConstants.PT_JUN_TACA_QUINOA_INFLADA_FRUTOS, MealConstants.PT_JUN_TABULE_TRIGO_SARRACENO_HORTELA, MealConstants.PT_JUN_SOPA_GRAO_BICO_COUVE_LOMBARDA},
            {MealConstants.PT_JUN_PANQUECA_CHARUTO_REQUEIJAO, MealConstants.PT_JUN_HAMBURGUER_FEIJAO_FRADE_ARROZ_ESPREGUIADO, MealConstants.PT_JUN_CREME_BETERRABA_QUENTE_NOZ_MOSCADA},
            {MealConstants.PT_JUN_BARRINHA_AVEIA_TARTARO_FRUTA, MealConstants.PT_JUN_QUICHE_BATATA_DOCE_ESPINAFRE, MealConstants.PT_JUN_SOPA_CEBOLA_FRANCESA_TORRADA},
            {MealConstants.PT_JUN_SCONES_INTEGRAIS_PASSO_OESTE, MealConstants.PT_JUN_TOFU_BROA_FORNO_COENTROS, MealConstants.PT_JUN_CREME_CORACAO_ALFACE_ERVIHAS},
            {MealConstants.PT_JUN_BATIDO_VERDE_COUVE_GALEGA_MACA, MealConstants.PT_JUN_SALADA_MACARRAO_TRIGO_INTEGRAL_PICLES, MealConstants.PT_JUN_SOPA_BATATA_DOCE_ESPINAFFRE},
            {MealConstants.PT_JUN_FOCACCIA_ALECRIM_TOMATE_CHERRY, MealConstants.PT_JUN_ESTUFADO_GRAO_BICO_ESPINAFRES_COMINHOS, MealConstants.PT_JUN_CREME_AIPO_MAC_VERDE_QUENTE},
            {MealConstants.PT_JUN_PUDIM_TAPIOCA_LEITE_COCO, MealConstants.PT_JUN_PAELLA_FALSA_TRIGO_SARRACENO, MealConstants.PT_JUN_SOPA_TRIGO_SARRACENO_LEGUMES},
            {MealConstants.PT_JUN_TORRADA_MANTEIGA_SEMENTES_ABOBORA, MealConstants.PT_JUN_SALTEADO_SEITAN_MOLHO_CERVEJA, MealConstants.PT_JUN_CREME_NABIÇAS_TRADICIONAL_MINHO},
            {MealConstants.PT_JUN_PAPA_PAINCO_CREMOSA_CANELA, MealConstants.PT_JUN_KEDGEREE_VEGANO_ARROZ_CURCUMA, MealConstants.PT_JUN_SOPA_MISO_TOFU_ALGAS_WAKAME},
            {MealConstants.PT_JUN_CRUMPETS_AVEIA_GELEIA_FRUTA, MealConstants.PT_JUN_WRAP_QUENTE_FEIJAO_ENCARNADO, MealConstants.PT_JUN_CREME_REPOLHO_BRANCO_GRAO},
            {MealConstants.PT_JUN_BOLO_CHAVENA_CACAO_MICROONDAS, MealConstants.PT_JUN_TACOS_JACKFRUIT_MOLHO_BARBECUE, MealConstants.PT_JUN_SOPA_AZEDA_LENTILHAS_LIMON},
            {MealConstants.PT_JUN_TORRADA_PATE_LENTILHAS_ERVAS, MealConstants.PT_JUN_RISOTO_BETERRABA_CREMOSO, MealConstants.PT_JUN_CREME_ABOBORINHA_ALHO_PORRO},
            {MealConstants.PT_JUN_BATIDO_GOIABA_POLPA_COCO, MealConstants.PT_JUN_SALADA_LENTILHAS_BELUGA_NURZ_MOSTARDA, MealConstants.PT_JUN_SOPA_RAIZES_PASTINACA_CENOURA},
            {MealConstants.PT_JUN_MINI_QUICHE_SEM_MASSA_LEGUMES, MealConstants.PT_JUN_MAC_AND_CHEESE_VEGAN_ABOBORA, MealConstants.PT_JUN_CREME_FOLHAS_KALE_BATATA_DOCE},
            {MealConstants.PT_JUN_BOLACHAS_AVEIA_BANANA_3_ING, MealConstants.PT_JUN_EMPADAO_SOJA_TEXTURIZADA_BATATA, MealConstants.PT_JUN_SOPA_BARRANQUENHA_LEGUMES_PIMENTA}
    };

    private final String[][] mealSuggestionsPtJul = {
            {MealConstants.PT_JUL_SMOOTHIE_NECTARINA_GOJI, MealConstants.PT_JUL_SALADA_FEIJAO_FRADE_PIMENTO_COENTROS, MealConstants.PT_JUL_GASPACHO_TOMATE_FRIO_CEBOLINHO},
            {MealConstants.PT_JUL_AVEIA_ADORMECIDA_AMORA_SILVESTRE, MealConstants.PT_JUL_SALADA_QUINOA_MANGA_CHILI, MealConstants.PT_JUL_TOFU_GRELHADO_SALADA_PEPINO_MENTA},
            {MealConstants.PT_JUL_TORRADA_ABACATE_GELADO_LIMA, MealConstants.PT_JUL_MASSA_FRESCA_TOMATE_CHERRY_MANJERICAO, MealConstants.PT_JUL_CREME_FRIO_MELAO_REFRESCANTE},
            {MealConstants.PT_JUL_PUDIM_CHIA_FRAMBOESA_HORTELA, MealConstants.PT_JUL_BURRITO_VEG_FEIJAO_FRITO_PIMENTOS, MealConstants.PT_JUL_SALADA_MELANCIA_RUCULA_QUEIJO_FETA},
            {MealConstants.PT_JUL_PANQUECAS_MIRTILO_LIMAO, MealConstants.PT_JUL_RISOTO_HORTELA_LIMAO_JUL, MealConstants.PT_JUL_CREME_CENOURA_FRESCO_SUMO_LIMAO},
            {MealConstants.PT_JUL_SMOOTHIE_BOWL_FRUTOS_ROXOS, MealConstants.PT_JUL_SALADA_LENTILHAS_ABACAXI_RUCULA, MealConstants.PT_JUL_COGUMELOS_SALTEADOS_ALHO_FRESCO},
            {MealConstants.PT_JUL_TACA_IOGURTE_GRENADA, MealConstants.PT_JUL_TORTILHA_BATATA_CURGETE_CEBOLA, MealConstants.PT_JUL_SOPA_FEIJAO_VERDE_AZEITE_ALHO},
            {MealConstants.PT_JUL_TORRADA_FETA_MELANCIA, MealConstants.PT_JUL_ARROZ_COENTROS_TOFU_FUMADO, MealConstants.PT_JUL_SALADA_RUCULA_AMEIXA_AMENDOA},
            {MealConstants.PT_JUL_MEXIDO_TOFU_TOMATE_PIMENTO, MealConstants.PT_JUL_SALADA_GRAO_PEPINELLA_RABANETE, MealConstants.PT_JUL_CREME_FRIO_ERVILHAS_MENT},
            {MealConstants.PT_JUL_AVEIA_FRIA_MELAO_ALBICOQUE, MealConstants.PT_JUL_COUSCOUS_JULHO_LEGUMES_GRELHADOS, MealConstants.PT_JUL_OMELETE_TOMATE_CHERRY_FRESCO},
            {MealConstants.PT_JUL_SMOOTHIE_CEREJA_CACAU, MealConstants.PT_JUL_LASANHA_FRIA_CURGETE_TOMATE, MealConstants.PT_JUL_SOPA_LEGUMES_JULHO_MANJERICAO},
            {MealConstants.PT_JUL_PANQUECAS_COCO_MANGA_FRESCA, MealConstants.PT_JUL_SALADA_MACARRAO_AZEITONA_CAPRESE, MealConstants.PT_JUL_SALADA_COLESLAW_IOGURTE_HORTELA},
            {MealConstants.PT_JUL_TORRADA_HUMUS_CURGETE, MealConstants.PT_JUL_ESTUFADO_GRAO_TOMATE_MANJERICAO, MealConstants.PT_JUL_CREME_ABOBORA_LEVE_SOUCHE},
            {MealConstants.PT_JUL_MUESLI_TROPICAL_ANANAS, MealConstants.PT_JUL_HAMBURGUER_LENTILHAS_SALADA_VERAO, MealConstants.PT_JUL_TOFU_MEXIDO_TOMATE_CHERRY_MANJERICAO},
            {MealConstants.PT_JUL_PAPA_ARROZ_MARACUJA, MealConstants.PT_JUL_SALADA_QUINOA_CEREJA_FETA, MealConstants.PT_JUL_SOPA_LENTILHAS_VERAO_RASPAS_LIMAO},
            {MealConstants.PT_JUL_SMOOTHIE_PAPAIA_MANJERICAO, MealConstants.PT_JUL_ARROZ_TOMATE_MALANDRINHO_COENTROS, MealConstants.PT_JUL_SALADA_TZATZIKI_PEPINO_MENTA_AZEITE},
            {MealConstants.PT_JUL_TORRADA_ABACATE_SOUCHE_ABOBORA, MealConstants.PT_JUL_QUICHE_CURGETE_TOMATE_CHERRY, MealConstants.PT_JUL_CREME_COUVE_FLOR_FRIO_FRANCES},
            {MealConstants.PT_JUL_TACA_ACAI_FRAMBOESA_GRANOLA, MealConstants.PT_JUL_SALADA_PASTA_GRAO_AZEITONA, MealConstants.PT_JUL_WRAP_HUMUS_TOMATE_PEPINO_FRESCO},
            {MealConstants.PT_JUL_PAPAS_AVEIA_FRIAS_HORTELA_CHIA, MealConstants.PT_JUL_MASSA_PESTO_RUCULA_TOMATE_SECO, MealConstants.PT_JUL_SOPA_GRAO_CURGETE_FOLHAS_MANJERICAO},
            {MealConstants.PT_JUL_SMOOTHIE_BOWL_MELAO_CELESTE, MealConstants.PT_JUL_GRATINADO_BERINJELA_TOMATE_FRESCO, MealConstants.PT_JUL_SALADA_ESPINAFRE_MANGA_PINDAS},
            {MealConstants.PT_JUL_AVEIA_NOITE_PESSEGO_AMENDOA, MealConstants.PT_JUL_SALADA_LENTILHAS_AMEIXA_AVOCADO, MealConstants.PT_JUL_SOPA_TOMATE_PEPINO_SOPA_FRESCA},
            {MealConstants.PT_JUL_PANQUECAS_INTEGRAIS_AMEIXA_FRESCA, MealConstants.PT_JUL_RISOTO_TOMATE_CONCHAS_BASILICO, MealConstants.PT_JUL_OVOS_ESCALFADOS_MOLHO_TOMATE_JULHO},
            {MealConstants.PT_JUL_TORRADA_RICOTA_FIGO_MEL, MealConstants.PT_JUL_CANELONES_VEGAN_CURGETE, MealConstants.PT_JUL_SOPA_MINESTRONE_JULHO_LEVE},
            {MealConstants.PT_JUL_IOGURTE_GRANOLA_CEREJA, MealConstants.PT_JUL_SALADA_QUINOA_MELANCIA_HORTELA, MealConstants.PT_JUL_SALADA_BETERRABA_LARANJA_NOZES_JUL},
            {MealConstants.PT_JUL_SMOOTHIE_VERDE_COUVE_MELANCIA, MealConstants.PT_JUL_CARIL_ALBICOQUE_GRAO_BICO, MealConstants.PT_JUL_CREME_CURGETE_COENTROS_HORTELA},
            {MealConstants.PT_JUL_PUDIM_CHIA_PESSEGO_CARECA, MealConstants.PT_JUL_SALTEADO_TOFU_MILHO_DOCE, MealConstants.PT_JUL_PORTOBELLO_GRELHADO_TOMATE_MANJERICAO},
            {MealConstants.PT_JUL_TORRADA_MANTEIGA_AMENDOIM_FRAMBOESA, MealConstants.PT_JUL_GAZPACHO_ALGARVIO_PIMENTOS_PEPINO, MealConstants.PT_JUL_SOPA_ALHO_FRANCES_CURGETE_CREME_LEVE},
            {MealConstants.PT_JUL_AVEIA_CHOCOLATE_NEGRO_AMORA, MealConstants.PT_JUL_SALADA_MACARRAO_CAPRESE_JULHO, MealConstants.PT_JUL_SALADA_ALFACE_MILHO_AVOCADO_FRESCO},
            {MealConstants.PT_JUL_SMOOTHIE_UVA_PRETA_FRAMBOESA, MealConstants.PT_JUL_EMPADAO_BATATA_DOCE_LENTILHAS_VERMELHAS, MealConstants.PT_JUL_CREME_ESPARGOS_FRIO_FOLHAS_MENTA},
            {MealConstants.PT_JUL_PANQUECAS_AVEIA_SOUCHE_LINHACA, MealConstants.PT_JUL_PAELLA_VEGETARIANA_VERAO_JULHO, MealConstants.PT_JUL_TOFU_SALTEADO_MANGA_PIMENTOS_DOCES},
            {MealConstants.PT_JUL_TACA_IOGURTE_FRUTOS_SILVESTRES, MealConstants.PT_JUL_SALADA_GRAO_MANGA_RUCULA, MealConstants.PT_JUL_SOPA_JULIANA_REPOLHO_CENOURA}
    };

    private final String[][] mealSuggestionsPtAgo = {
            {MealConstants.PT_AGO_PANQUECA_MILHO_DOCE, MealConstants.PT_AGO_CEVICHE_PALMITO_MANGA_COENTROS, MealConstants.PT_AGO_WRAP_QUENTE_FEIJAO_ENCARNADO},
            {MealConstants.PT_AGO_OVERNIGHT_TROPICAL_COCO_ANANAS, MealConstants.PT_AGO_TABULE_BULGUR_HORTELA_GRAO, MealConstants.PT_AGO_BRUSCHETTA_TAPENADE_TOMATE_SECO},
            {MealConstants.PT_AGO_TORRADA_SMUSH_ERVIHA_HORTELA, MealConstants.PT_AGO_ESPETADAS_TOFU_FUMADO_PIMENTON, MealConstants.PT_AGO_SALADA_QUENTE_BATATA_DOCE_LENTILHA},
            {MealConstants.PT_AGO_PUDIM_CHIA_MELOA_GENGIBRE, MealConstants.PT_AGO_SALADA_CROCANTE_REPOLHO_AMENDOIM, MealConstants.PT_AGO_TORTILHA_ESPINAFRES_BATATA_DOCE_FORNO},
            {MealConstants.PT_AGO_BOLO_CANECA_ALFARROBA_NOZ, MealConstants.PT_AGO_BURRITO_FRIO_HUMUS_ALFAFA, MealConstants.PT_AGO_ESPARGUETE_CURGETE_PESTO_AVELA},
            {MealConstants.PT_AGO_WAFFLE_AVEIA_COMPOTA_FIGO, MealConstants.PT_AGO_TACOS_JACKFRUIT_BARBECUE_MILHO, MealConstants.PT_AGO_TOFU_GRELHADO_SOJA_GENGIBRE},
            {MealConstants.PT_AGO_TACA_AÇAI_RODOLES_BANANA_GRANOLA, MealConstants.PT_AGO_NOODLES_ARROZ_FRIOS_SESAMO_LIMA, MealConstants.PT_AGO_MASSA_ORZO_TOMATE_FORNO_MANJERICAO},
            {MealConstants.PT_AGO_PÃO_FRIGIDEIRA_RAPIDO_SÉSAMO, MealConstants.PT_AGO_FEIJOADA_COGUMELOS_PLEUROTUS, MealConstants.PT_AGO_RAMEN_CARIL_CALDO_LEGUMES_TOFU},
            {MealConstants.PT_AGO_BATIDO_ENERGIA_PAPAIA_AVEIA, MealConstants.PT_AGO_STIR_FRY_SEITAN_BROCOLOS_ALHO, MealConstants.PT_AGO_CARPACCIO_CURGETE_LIMAO_PINHOES},
            {MealConstants.PT_AGO_TORRADA_PATE_AZEVITONA_VERDE, MealConstants.PT_AGO_SALADA_QUINOA_VERMELHA_EDAMAME, MealConstants.PT_AGO_SALADA_FEIJAO_MANTEIGA_TOMATE_CHERRY},
            {MealConstants.PT_AGO_CREPE_POLVILHADO_CANELA_MACA, MealConstants.PT_AGO_CHILI_VEGANO_TRES_FEIJOES, MealConstants.PT_AGO_OVO_ESCALFADO_ESTUFADO_TOMATE_ALHO},
            {MealConstants.PT_AGO_IOGURTE_COCO_BAGAS_GOJI_CRUNCH, MealConstants.PT_AGO_MAC_AND_CHEESE_ABOBORA_CAJU, MealConstants.PT_AGO_SALADA_FRESCA_BELDROEGAS_QUINOA},
            {MealConstants.PT_AGO_MUFFIN_SALGADO_GRAO_LEGUMES, MealConstants.PT_AGO_KEDGEREE_VEGANO_ARROZ_CURCUMA, MealConstants.PT_AGO_TACOS_FALAFEL_ESMAGADO_PICO_GALLO},
            {MealConstants.PT_AGO_SMOOTHIE_VERDE_ESPINAFRE_MANGA, MealConstants.PT_AGO_XAREM_ALGARVIO_COGUMELOS_SALTEADOS, MealConstants.PT_AGO_SALADA_LENTILHAS_VERDES_MELOA_FETA},
            {MealConstants.PT_AGO_TORRADA_RICOTA_AMIXA_FRESCA, MealConstants.PT_AGO_LASANHA_LENTILHAS_FOLHAS_COUVE, MealConstants.PT_AGO_SALADA_FUSILLI_TOMATE_SECO_RUCULA},
            {MealConstants.PT_AGO_TACA_QUINOA_DOCE_LEITE_COCO, MealConstants.PT_AGO_GNOCCHI_BATATA_SALVIA_AZEITE, MealConstants.PT_AGO_TARTE_FOLHADA_TOMATE_MANJERICAO},
            {MealConstants.PT_AGO_SCOTTISH_PORRIDGE_SALGADA_AZEITE, MealConstants.PT_AGO_FALAFEL_FORNO_MOLHO_TAHINI, MealConstants.PT_AGO_SALADA_MACARRAO_FRIO_TORTILHA_AZEITE},
            {MealConstants.PT_AGO_BATIDO_CACAU_PURO_MANTEIGA_AMENDOIM, MealConstants.PT_AGO_COUSCOUS_ISRAELITA_VEGETAIS_FORNO, MealConstants.PT_AGO_WRAPS_FOLHA_COUVE_LENTILHAS_CENOURA},
            {MealConstants.PT_AGO_GALETTE_RUSTICA_MORANGO_MANJERICAO, MealConstants.PT_AGO_HAMBURGUER_FEIJAO_FRADE_ARROZ, MealConstants.PT_AGO_SALADA_TRIGO_SARRACENO_NISSARDA_VEG},
            {MealConstants.PT_AGO_TORRADA_GELEIA_PIMENTO_QUEIJO_VEG, MealConstants.PT_AGO_POLENTA_FORNO_MOLHO_FUNGHI, MealConstants.PT_AGO_PAELLA_VERAO_ALCACHOFRA_PIMENTOS},
            {MealConstants.PT_AGO_BARRINHA_CRUDA_TAMARA_AVELA, MealConstants.PT_AGO_SALADA_LENTILHAS_BELUGA_NOZ_MOSTARDA, MealConstants.PT_AGO_CANELONES_FRIOS_PEPINO_CREME_CAJU},
            {MealConstants.PT_AGO_SUMO_PRENSADO_MELANCIA_LIMA, MealConstants.PT_AGO_TABULE_TRIGO_SARRACENO_PEPINELLA, MealConstants.PT_AGO_SALADA_QUINOA_ABACATE_MILHO_DOCE},
            {MealConstants.PT_AGO_PANQUECA_TRIGO_SARRACENO_FRUTOS, MealConstants.PT_AGO_ESTUFADO_LENTILHAS_ABOBORA_MANTEIGA, MealConstants.PT_AGO_SALADA_FEIJAO_MANTEIGA_PESSEGO_RUCULA},
            {MealConstants.PT_AGO_SCONES_AVEIA_PASSA_UVA, MealConstants.PT_AGO_QUICHE_BATATA_DOCE_ESPINAFRE_TOFU, MealConstants.PT_AGO_SALADA_QUINOA_VERMELHA_ROMA_COENTRO},
            {MealConstants.PT_AGO_BATIDO_GOIABA_POLPA_FRESCA, MealConstants.PT_AGO_TOFU_BROA_FORNO_COENTROS, MealConstants.PT_AGO_FOCACCIA_ALECRIM_TOMATE_CHERRY},
            {MealConstants.PT_AGO_TORRADA_MANTEIGA_CAJU_SEMENTES, MealConstants.PT_AGO_ALHO_FRANCES_RECHEADO_QUINOA, MealConstants.PT_AGO_SALADA_QUENTE_VAGENS_FEIJAO_TOFU},
            {MealConstants.PT_AGO_TACA_KEFIR_UVA_CRISP_PAINÇO, MealConstants.PT_AGO_EMPADAO_SOJA_TEXTURIZADA_PURE, MealConstants.PT_AGO_SALADA_TOMATE_CORAÇÃO_CEBOLA_ROXA},
            {MealConstants.PT_AGO_PUDIM_LINHAÇA_PERA_ROCHA, MealConstants.PT_AGO_BURRITO_BOWL_ARROZ_INTEGRAL, MealConstants.PT_AGO_OMELETE_CLARAS_TOMATE_CHERRY_OREGAO},
            {MealConstants.PT_AGO_MINI_QUICHE_TOFU_SEM_MASSA, MealConstants.PT_AGO_SALADA_POTATO_SALAD_MAIONESE_VEG, MealConstants.PT_AGO_SALADA_REPOLHO_CENOURA_RALADA_MACA},
            {MealConstants.PT_AGO_BOLACHAS_AVEIA_BANANA_CHOCOLATE, MealConstants.PT_AGO_PAELLA_FALSA_TRIGO_SARRACENO_ERVIHA, MealConstants.PT_AGO_SALADA_FRO_BETERRABA_COZIDA_AGRIAO},
            {MealConstants.PT_AGO_BRUSCHETTA_TOMATE_RALADO_AZEITE, MealConstants.PT_AGO_SUSHIBOWL_ARROZ_AVOCADO_ALGA_NORI, MealConstants.PT_AGO_SALADA_RUCULA_PERA_ROCHA_NOZES}
    };

    private final String[][] mealSuggestionsPtSet = {
            {MealConstants.PT_SET_PAPA_AVEIA_MACA_CANELA_FORNO, MealConstants.PT_SET_ARROZ_FORNO_COGUMELOS_CASTANHAS, MealConstants.PT_SET_JAN_BATATA_DOCE_FIGOS},
            {MealConstants.PT_SET_TORRADA_MANTEIGA_AVELA_FIGO_CALDA, MealConstants.PT_SET_ESTUFADO_GRAO_ABOBORA_MENINA, MealConstants.PT_SET_JAN_RISOTO_UVAS_COGUMELOS},
            {MealConstants.PT_SET_PANQUECA_ABOBORA_ESPECIARIAS, MealConstants.PT_SET_FEIJOADA_TRANSMONTANA_VEGETARIANA, MealConstants.PT_SET_JAN_TOFU_GRELHADO_MACA},
            {MealConstants.PT_SET_BATIDO_OUTONO_PERA_ROCHA_NOZ, MealConstants.PT_SET_RISOTO_ABOBORA_ASSADA_SALVIA, MealConstants.PT_SET_JAN_QUICHE_ALHO_FRANCES_COGUMELO},
            {MealConstants.PT_SET_TACA_IOGURTE_UVAS_VINDIMA_GRANOLA, MealConstants.PT_SET_MASSA_INTEGRAL_COGUMELOS_PORTOBELLO, MealConstants.PT_SET_JAN_ESTUFADO_GRAO_ESPINAFRE},
            {MealConstants.PT_SET_PUDIM_CHIA_ROMA_SABUGUEIRO, MealConstants.PT_SET_EMPADAO_LENTILHAS_PURE_BATATA_DOCE, MealConstants.PT_SET_JAN_POLENTA_ABOBORA_SALVIA},
            {MealConstants.PT_SET_TORRADA_RICOTA_PERA_GRELHADA_MEL, MealConstants.PT_SET_CARIL_GRAO_BICO_BATATA_DOCE, MealConstants.PT_SET_JAN_MASSA_BERINGELA_ASSADA},
            {MealConstants.PT_SET_MUFFIN_INTEGRAL_ALFARROBA_NOZ, MealConstants.PT_SET_SALADA_QUENTE_TRIGO_SARRACENO_COGUMELO, MealConstants.PT_SET_JAN_BURRITO_FEIJAO_ABOBORINHA},
            {MealConstants.PT_SET_MEXIDO_TOFU_ESPINAFRE_ALHO_PORRO, MealConstants.PT_SET_LASANHA_ESPINAFRE_RICOTA_CAJU, MealConstants.PT_SET_JAN_SEITAN_VINDIMA},
            {MealConstants.PT_SET_PAPA_ARROZ_INTEGRAL_COCO_LARANJA, MealConstants.PT_SET_HAMBURGUER_LENTILHAS_ARROZ_ESCAROLA, MealConstants.PT_SET_JAN_FRITTATA_TOMATE_MANJERICAO},
            {MealConstants.PT_SET_CREPE_AVEIA_CREME_CHOCOLATE_NEGRO, MealConstants.PT_SET_COUSCOUS_MARROQUINO_LEGUMES_RAIZ, MealConstants.PT_SET_JAN_TARTE_FOLHADA_FIGO},
            {MealConstants.PT_SET_BOLO_CHAVENA_MACA_AMENDOA_MICROONDAS, MealConstants.PT_SET_TOFU_ESTUFADO_MOLHO_VINHO_TINTO, MealConstants.PT_SET_JAN_LENTILHAS_ESTUFADAS_KALE},
            {MealConstants.PT_SET_TORRADA_SMASH_GRAO_BICO_PIMENTA, MealConstants.PT_SET_CANELONES_RECHEADOS_LENTILHAS_TOMATE, MealConstants.PT_SET_JAN_GNOCCHI_TOMATE_ASSADO},
            {MealConstants.PT_SET_BOLO_FRIGIDEIRA_BATATA_DOCE_NOZ, MealConstants.PT_SET_ALMONDEGAS_FEIJAO_PRETO_ESPAGUETE, MealConstants.PT_SET_JAN_TEMPEH_FORNO_PIMENTOS},
            {MealConstants.PT_SET_GRANOLA_QUENTE_BEBIDA_AVEIA_PASSA, MealConstants.PT_SET_STIR_FRY_TEMPEH_BROCOLOS_SESAMO, MealConstants.PT_SET_JAN_SALADA_QUENTE_QUINOA_FIGO},
            {MealConstants.PT_SET_PUDIM_LINHACA_SABOR_TARTE_MACA, MealConstants.PT_SET_QUICHE_COGUMELOS_ALHO_FRANCES, MealConstants.PT_SET_JAN_TROUXAS_COUVE_GRAO},
            {MealConstants.PT_SET_TORRADA_HUMUS_PIMENTOS_PADRON, MealConstants.PT_SET_BURRITO_BOWL_QUINOA_FEIJAO_PRETO, MealConstants.PT_SET_JAN_HAMBURGUER_FEIJAO_ARROZ},
            {MealConstants.PT_SET_BATIDO_ROXO_UVA_PRETA_SEMENTES, MealConstants.PT_SET_GNOCCHI_ABOBORA_CREME_NOZ, MealConstants.PT_SET_JAN_ALMONDEGAS_LENTILHAS_ESPAGUETE},
            {MealConstants.PT_SET_SCONES_ESPELTA_AROMA_ERVA_DOCE, MealConstants.PT_SET_XAREM_ALGARVIO_BROCOLOS_TOFU, MealConstants.PT_SET_JAN_COUSCOUS_LEGUMES_GRELHADOS},
            {MealConstants.PT_SET_PAPA_PAINCO_COMPOTA_PERA_ROCHA, MealConstants.PT_SET_SALADA_QUENTE_GRAO_BETERRABA_ASSADA, MealConstants.PT_SET_JAN_WRAP_TOFU_FUMADO_ESPINAFRE},
            {MealConstants.PT_SET_BARRINHA_AVEIA_FORNO_ALFARROBA, MealConstants.PT_SET_PAELLA_OUTONO_COGUMELOS_ALCACHOFRA, MealConstants.PT_SET_JAN_TACOS_COGUMELOS_SHIITAKE},
            {MealConstants.PT_SET_TORRADA_CREME_AMENDOIM_MACA_QUENTE, MealConstants.PT_SET_SEITAN_ASSADO_FORNO_BATATINHAS, MealConstants.PT_SET_JAN_XAREM_LIGEIRO_COENTROS},
            {MealConstants.PT_SET_BATIDO_VERDE_KALE_PERA_GENGIBRE, MealConstants.PT_SET_FAVAL_A_PORTUGUESA_VEGANO, MealConstants.PT_SET_JAN_BIFE_SEITAN_ALHO_ALECRIM},
            {MealConstants.PT_SET_TACA_KEFIR_DOCE_FIGO_LINHACA, MealConstants.PT_SET_WRAP_QUENTE_GRAO_ESPINAFRE_TAHINI, MealConstants.PT_SET_JAN_CURGETE_RECHEADA_LENTILHAS},
            {MealConstants.PT_SET_PANQUECA_ALFARROBA_CALDA_FRAMBOESA, MealConstants.PT_SET_TACOS_COGUMELOS_SHIITAKE_CEBOLA, MealConstants.PT_SET_JAN_CREPE_GRAO_COGUMELOS},
            {MealConstants.PT_SET_GALETTE_INTEGRAL_UVAS_ASSADAS, MealConstants.PT_SET_RISOTO_COGUMELOS_PORCINI_TOMILHO, MealConstants.PT_SET_JAN_MIGAS_TOMATE_TOFU},
            {MealConstants.PT_SET_TORRADA_PATE_COGUMELOS_ALHO, MealConstants.PT_SET_ESTUFADO_FEIJAO_BRANCO_COUVE_GALEGA, MealConstants.PT_SET_JAN_STIR_FRY_BROCOLOS_AMENDOIM},
            {MealConstants.PT_SET_SMOOTHIE_BOWL_ABOBORA_AVEIA_CHIA, MealConstants.PT_SET_MAC_AND_CHEESE_BATATA_DOCE_CAJU, MealConstants.PT_SET_JAN_TARTE_RUSTICA_ABOBORA},
            {MealConstants.PT_SET_PAPA_TRIGO_SARRACENO_CHOCOLATE, MealConstants.PT_SET_TORTILHA_FORNO_LEGUMES_OUTONO, MealConstants.PT_SET_JAN_SALADA_WARM_GRAO_BETERRABA},
            {MealConstants.PT_SET_TORRADA_REQUEIJAO_VEG_DOCE_MACA, MealConstants.PT_SET_SALADA_WARM_LENTILHAS_BELUGA_PERA, MealConstants.PT_SET_JAN_MAC_CHEESE_ABOBORA_CAJU}
    };

    private final String[][] mealSuggestionsPtOut = {
            {MealConstants.PT_OUT_BRUSCHETTA_BROA_ABOBORA, MealConstants.PT_OUT_COZIDO_RUSTICO_LEGUMES, MealConstants.PT_OUT_BATATA_DOCE_RECHEADA},
            {MealConstants.PT_OUT_BAKED_OATS_REINETA, MealConstants.PT_OUT_ASSADO_TABULEIRO_TEMPEH, MealConstants.PT_OUT_POLENTA_COGUMELOS},
            {MealConstants.PT_OUT_PAPA_CEVADA_DIOSPIRO, MealConstants.PT_OUT_RANCHO_VEGANO_GRAO, MealConstants.PT_OUT_EMPADAO_COUVE_FLOR},
            {MealConstants.PT_OUT_TORRADA_MARMELADA_VEG, MealConstants.PT_OUT_TARTE_RUSTICA_GRELOS, MealConstants.PT_OUT_TOFU_CROSTA_AVELA},
            {MealConstants.PT_OUT_PANQUECA_BOLOTA_PINHAO, MealConstants.PT_OUT_ESTUFADO_LENTILHAS_CASTANHAS, MealConstants.PT_OUT_ABOBORA_FORNO_TAHINI},
            {MealConstants.PT_OUT_WAFFLE_ALFARROBA_NOZ, MealConstants.PT_OUT_ARROZ_MALANDRO_COGUMELOS, MealConstants.PT_OUT_FRITTATA_ALHO_FRANCES},
            {MealConstants.PT_OUT_PUDIM_CHIA_KAKI_LARANJA, MealConstants.PT_OUT_SEITAN_PIMENTA_TERRA, MealConstants.PT_OUT_COGUMELOS_PORTOBELLO_RECHEADOS},
            {MealConstants.PT_OUT_TACA_BATATA_DOCE_COMPOTA, MealConstants.PT_OUT_EMPADAO_VEGANO_ALHO_FRANCES, MealConstants.PT_OUT_ESTUFADO_LENTILHAS_COUVE},
            {MealConstants.PT_OUT_CREPE_ESPELTA_AMENDOA, MealConstants.PT_OUT_CARIL_ABOBORA_MANTEIGA_GRAO, MealConstants.PT_OUT_COUVE_CORACAO_RECHEADA},
            {MealConstants.PT_OUT_MUFFIN_CASTANHA_CHOCOLATE, MealConstants.PT_OUT_FEIJOADA_COUVE_LOMBARDA, MealConstants.PT_OUT_SALADA_QUENTE_KALE},
            {MealConstants.PT_OUT_TOFU_MEXIDO_ALHO_PORRO, MealConstants.PT_OUT_RISOTO_CEVADA_COGUMELOS, MealConstants.PT_OUT_STROGANOFF_COGUMELOS},
            {MealConstants.PT_OUT_PAPA_CENTEIO_MACA_ASSADA, MealConstants.PT_OUT_TOFU_LAGAREIRO_BATATA_MURRO, MealConstants.PT_OUT_QUICHE_ALHO_PORRO},
            {MealConstants.PT_OUT_BATIDO_QUENTE_AVELA_AVEIA, MealConstants.PT_OUT_MASSA_FORNO_ABOBORA_SALVIA, MealConstants.PT_OUT_CARIL_RECONFORTANTE_LEGUMES},
            {MealConstants.PT_OUT_SCONES_INTEGRAIS_PASSAS, MealConstants.PT_OUT_LASANHA_COGUMELOS_CREME_AVELA, MealConstants.PT_OUT_MIGAS_GRELOS_BROA},
            {MealConstants.PT_OUT_TORRADA_SMASH_FEIJAO_ALHO, MealConstants.PT_OUT_ALMONDEGAS_BOLOTA_MOLHO_TOMATE, MealConstants.PT_OUT_GNOCCHI_ABOBORA_SALVIA},
            {MealConstants.PT_OUT_BOLO_CANECA_REINETA_CANELA, MealConstants.PT_OUT_QUICHE_SEM_MASSA_GRELOS_TOFU, MealConstants.PT_OUT_BIFE_COUVE_FLOR},
            {MealConstants.PT_OUT_GRANOLA_QUENTE_ROMA, MealConstants.PT_OUT_XAREM_ALGARVIO_AMEIJOA_VEG, MealConstants.PT_OUT_BRUSCHETTA_QUENTE_PATE},
            {MealConstants.PT_OUT_PUDIM_LINHACA_MARMELO, MealConstants.PT_OUT_GNOCCHI_CASTANHA_MANTEIGA_SALVIA, MealConstants.PT_OUT_TEMPEH_GRELHADO_BROCOLOS},
            {MealConstants.PT_OUT_TACA_IOGURTE_COCO_AVELA, MealConstants.PT_OUT_CALDEIRADA_VEGAN_PALMITO_RAIZES, MealConstants.PT_OUT_PATANISCAS_LEGUMES_ARROZ},
            {MealConstants.PT_OUT_GALETTE_OUTONO_PERA, MealConstants.PT_OUT_ROLO_LENTILHAS_RECHEADO_ALHO, MealConstants.PT_OUT_ESTUFADO_FEIJAO_BRANCO},
            {MealConstants.PT_OUT_BRUSCHETTA_COGUMELOS_ALECRIM, MealConstants.PT_OUT_BURRITO_QUENTE_FEIJAO_PRETO_ABOBORA, MealConstants.PT_OUT_PASTEL_FORNO_LENTILHAS},
            {MealConstants.PT_OUT_PANQUECA_CENTEIO_XAROPE, MealConstants.PT_OUT_TACOS_COGUMELOS_PLEUROTUS_CEBOLA, MealConstants.PT_OUT_SARRACENO_COGUMELOS},
            {MealConstants.PT_OUT_BOLO_FRIGIDEIRA_ABOBORA, MealConstants.PT_OUT_STIR_FRY_TEMPEH_REPOLHO_OUTONO, MealConstants.PT_OUT_QUINOA_OUTONO_FORNO},
            {MealConstants.PT_OUT_BATIDO_DIOSPIRO_GENGIBRE, MealConstants.PT_OUT_COUSCOUS_MARROQUINO_GRAO_PASSAS, MealConstants.PT_OUT_TARTE_FOLHADA_BETERRABA},
            {MealConstants.PT_OUT_TACA_KEFIR_NOZES_MEL, MealConstants.PT_OUT_FEIJAO_FRADE_ESTUFADO_COUVE_GALEGA, MealConstants.PT_OUT_MASSA_CREMOSA_CAJU},
            {MealConstants.PT_OUT_TORRADA_PATE_CASTANHA, MealConstants.PT_OUT_MARMITA_FORNO_BATATA_DOCE_BROCOLOS, MealConstants.PT_OUT_BURRITO_BOWL_NOITE},
            {MealConstants.PT_OUT_SMOOTHIE_KALE_MACA_REINETA, MealConstants.PT_OUT_CANELONES_RECHEADOS_ESPINAFRE_RICOTA, MealConstants.PT_OUT_CREPE_SALGADO_GRAO},
            {MealConstants.PT_OUT_PAPA_PAINCO_CACAU_NOZ, MealConstants.PT_OUT_CHILI_VEGAN_LENTILHAS_ABOBORA, MealConstants.PT_OUT_ESPETADAS_TOFU_LEGUMES},
            {MealConstants.PT_OUT_OVO_ESCALFADO_ESPINAFRE, MealConstants.PT_OUT_MIGAS_ALENTEJANAS_COGUMELOS_SILVESTRES, MealConstants.PT_OUT_PAPA_AVEIA_SALGADA},
            {MealConstants.PT_OUT_BOLACHAS_AVEIA_DIOSPIRO, MealConstants.PT_OUT_ESPAGUETE_INTEGRAL_ALHO_AZEITE_NOCES, MealConstants.PT_OUT_WRAP_FORNO_FEIJAO},
            {MealConstants.PT_OUT_WRAP_QUENTE_MANTEIGA_AMENDOIM, MealConstants.PT_OUT_TORTILHA_FORNO_LEGUMES_OUTONO, MealConstants.PT_OUT_XAREM_NOITE_COGUMELOS}
    };

    private final String[][] mealSuggestionsPtNov = {
            {MealConstants.PT_NOV_PEQ_PAPA_AVEIA_TANGERINA, MealConstants.PT_NOV_ALM_FEIJOADA_FEIJOCA_COGUMELOS, MealConstants.PT_NOV_JAN_SEITAN_SAN_MARTINHO},
            {MealConstants.PT_NOV_PEQ_TORRADA_DOCE_ABOBORA, MealConstants.PT_NOV_ALM_ASSADO_SÃO_MARTINHO, MealConstants.PT_NOV_JAN_FEIJOADA_FEIJOCAS},
            {MealConstants.PT_NOV_PEQ_PANQUECA_CASTANHA_CACAU, MealConstants.PT_NOV_ALM_RANCHO_VEGANO_GRÃO, MealConstants.PT_NOV_JAN_CEVADOTTO_COGUMELOS},
            {MealConstants.PT_NOV_PEQ_BOLO_CANECA_MARMELO, MealConstants.PT_NOV_ALM_ARROZ_GRELOS_PATANISCAS, MealConstants.PT_NOV_JAN_GRATINADO_BATATA_NABO},
            {MealConstants.PT_NOV_PEQ_WAFFLE_BATATA_DOCE, MealConstants.PT_NOV_ALM_ESTUFADO_LENTILHAS_CASTANHAS, MealConstants.PT_NOV_JAN_TOFU_FUMADO_GRELOS},
            {MealConstants.PT_NOV_PEQ_PUDIM_CHIA_DIOSPIRO, MealConstants.PT_NOV_ALM_ARROZ_FORNO_ABOBORA_GRAO, MealConstants.PT_NOV_JAN_HAMBURGUER_LENTILHAS},
            {MealConstants.PT_NOV_PEQ_TOFU_MEXIDO_GRELOS, MealConstants.PT_NOV_ALM_EMPADAO_SOJA_PURE_CASTANHA, MealConstants.PT_NOV_JAN_LASANHA_COUVE_PENCA},
            {MealConstants.PT_NOV_PEQ_CREPE_ESPELTA_MACA, MealConstants.PT_NOV_ALM_CARIL_QUENTE_GRAO_BATATA, MealConstants.PT_NOV_JAN_TEMPEH_PASTINACA_FORNO},
            {MealConstants.PT_NOV_PEQ_MUFFIN_AVEIA_NOZ, MealConstants.PT_NOV_ALM_MASSA_FORNO_ABOBORA_SALVIA, MealConstants.PT_NOV_JAN_CARIL_BELUGA_ESPINAFRES},
            {MealConstants.PT_NOV_PEQ_BATIDO_QUENTE_CHOCOLATE, MealConstants.PT_NOV_ALM_TOFU_LAGAREIRO_BATATA_MURRO, MealConstants.PT_NOV_JAN_CROQUETES_FEIJAO_ARROZ},
            {MealConstants.PT_NOV_PEQ_PAPA_CENTEIO_PASSA_UVA, MealConstants.PT_NOV_ALM_RISOTO_CEVADA_COGUMELOS, MealConstants.PT_NOV_JAN_TARTE_CEBOLA_SALVIA},
            {MealConstants.PT_NOV_PEQ_TORRADA_CREME_CAJU_ANIS, MealConstants.PT_NOV_ALM_LASANHA_LENTILHAS_LOMBARDA, MealConstants.PT_NOV_JAN_ALMONDEGAS_BOLOTA_PURE},
            {MealConstants.PT_NOV_PEQ_GRANOLA_INVERNO_LEITE, MealConstants.PT_NOV_ALM_ALMONDEGAS_BOLOTA_TOMATE, MealConstants.PT_NOV_JAN_GNOCCHI_ESPINAFRES_NOZ},
            {MealConstants.PT_NOV_PEQ_SCONES_BOLOTA_ERVA_DOCE, MealConstants.PT_NOV_ALM_TARTE_RUSTICA_GRELOS_TOFU, MealConstants.PT_NOV_JAN_ESPAGUETE_SARRACENO},
            {MealConstants.PT_NOV_PEQ_BRUSCHETTA_PASTINACA_FORNO, MealConstants.PT_NOV_ALM_COZIDO_LEGUMES_ENCHIDOS_VEG, MealConstants.PT_NOV_JAN_TROUXAS_GALEGA_QUINOA},
            {MealConstants.PT_NOV_PEQ_PAPA_PAINCO_PERA_COZIDA, MealConstants.PT_NOV_ALM_GNOCCHI_CASTANHA_MANTEIGA, MealConstants.PT_NOV_JAN_BATATA_ROXA_HUMUS},
            {MealConstants.PT_NOV_PEQ_TORRADA_HUMUS_PIMENTO, MealConstants.PT_NOV_ALM_CALDEIRADA_VEGAN_RAIZES, MealConstants.PT_NOV_JAN_ESTUFADO_GRAO_REPOLHO},
            {MealConstants.PT_NOV_PEQ_BATIDO_DIOSPIRO_AVEIA, MealConstants.PT_NOV_ALM_ROLO_LENTILHAS_RECHEADO, MealConstants.PT_NOV_JAN_POLENTA_FRITA_PORTOBELLO},
            {MealConstants.PT_NOV_PEQ_GALETTE_INTEGRAL_MACA, MealConstants.PT_NOV_ALM_BURRITO_FEIJAO_PRETO_ABOBORA, MealConstants.PT_NOV_JAN_QUICHE_NABO_ALHO_PORRO},
            {MealConstants.PT_NOV_PEQ_TACA_KEFIR_ROMA_AVELA, MealConstants.PT_NOV_ALM_TACOS_COGUMELOS_PLEUROTUS, MealConstants.PT_NOV_JAN_ESPETADAS_TEMPEH_CASTANHAS},
            {MealConstants.PT_NOV_PEQ_BARRINHA_AVEIA_FORNO, MealConstants.PT_NOV_ALM_STIR_FRY_TEMPEH_REPOLHO, MealConstants.PT_NOV_JAN_ARROZ_FORNO_LOMBARDA},
            {MealConstants.PT_NOV_PEQ_OVO_FORNO_ESPINAFRES, MealConstants.PT_NOV_ALM_COUSCOUS_GRAO_PASSAS_NOZ, MealConstants.PT_NOV_JAN_TOFU_LAGAREIRO_NOV},
            {MealConstants.PT_NOV_PEQ_SMOOTHIE_BOWL_KALE_PERA, MealConstants.PT_NOV_ALM_FEIJAO_FRADE_COUVE_GALEGA, MealConstants.PT_NOV_JAN_CHILI_LENTILHAS_CACAU},
            {MealConstants.PT_NOV_PEQ_PAPA_SARRACENO_CHOCOLATE, MealConstants.PT_NOV_ALM_MARMITA_BATATA_DOCE_BROCOLOS, MealConstants.PT_NOV_JAN_MIGAS_COUVE_PENCA},
            {MealConstants.PT_NOV_PEQ_TORRADA_REQUEIJAO_DOCE, MealConstants.PT_NOV_ALM_CANELONES_ESPINAFRE_RICOTA, MealConstants.PT_NOV_JAN_CRUMBLE_SALGADO_RAIZES},
            {MealConstants.PT_NOV_PEQ_BOLACHAS_INTEGRAIS_NOZ, MealConstants.PT_NOV_ALM_CHILI_VEGAN_LENTILHAS_ABOBORA, MealConstants.PT_NOV_JAN_WRAP_FEIJAO_FRADE},
            {MealConstants.PT_NOV_PEQ_TACA_IOGURTE_MACA_CANELA, MealConstants.PT_NOV_ALM_MIGAS_ALENTEJANAS_COGUMELOS, MealConstants.PT_NOV_JAN_MASSA_TOMATE_AZEITONA},
            {MealConstants.PT_NOV_PEQ_PUDIM_LINHACA_ABOBORA, MealConstants.PT_NOV_ALM_ESPAGUETE_ALHO_AZEITE_NOZ, MealConstants.PT_NOV_JAN_ESTUFADO_ERVILHAS_TOFU},
            {MealConstants.PT_NOV_PEQ_WRAP_QUENTE_BANANA_NOZ, MealConstants.PT_NOV_ALM_TORTILHA_FORNO_LEGUMES_OUT, MealConstants.PT_NOV_JAN_BOLINHOS_ARROZ_GRAO},
            {MealConstants.PT_NOV_PEQ_BRUSCHETTA_COGUMELOS_ALHO, MealConstants.PT_NOV_ALM_QUICHE_SEM_MASSA_GRELOS, MealConstants.PT_NOV_JAN_EMPADAO_COGUMELOS_DOCE}
    };

    private final String[][] mealSuggestionsPtDez = {
            {MealConstants.PT_DEZ_PEQ_RABANADA_FORNO_CANELA, MealConstants.PT_DEZ_ALM_ROUPA_VELHA_VEGAN, MealConstants.PT_DEZ_JAN_TOFU_ESPIRITUAL_NATAL},
            {MealConstants.PT_DEZ_PEQ_PAPA_AVEIA_NATAL_ESPECIARIAS, MealConstants.PT_DEZ_ALM_ASSADO_NATAL_SEITAN, MealConstants.PT_DEZ_JAN_POLENTA_INVERNO_COGUMELOS},
            {MealConstants.PT_DEZ_PEQ_TORRADA_DOCE_GILA_NOZ, MealConstants.PT_DEZ_ALM_FEIJOADA_TRANS_FEIJOCAS, MealConstants.PT_DEZ_JAN_BATATA_DOCE_RECHEADA_INVERNO},
            {MealConstants.PT_DEZ_PEQ_PANQUECA_GENGIBRE_MEL, MealConstants.PT_DEZ_ALM_ARROZ_FORNO_PASSA_PINHAO, MealConstants.PT_DEZ_JAN_EMPADAO_COUVE_FLOR_GRAO},
            {MealConstants.PT_DEZ_PEQ_BOLO_CANECA_CHOCOLATE_LARANJA, MealConstants.PT_DEZ_ALM_TOFU_BROA_COUVE_TRONCHUDA, MealConstants.PT_DEZ_JAN_ABOBORA_FORNO_ESPECIARIAS},
            {MealConstants.PT_DEZ_PEQ_WAFFLE_ALFARROBA_PASSAS, MealConstants.PT_DEZ_ALM_RANCHO_WINTER_VERSION, MealConstants.PT_DEZ_JAN_FRITTATA_INVERNO_ALHO_PORRO},
            {MealConstants.PT_DEZ_PEQ_PUDIM_CHIA_CLEMENTINA, MealConstants.PT_DEZ_ALM_RISOTO_ABOBORA_NOZ_MOSCADA, MealConstants.PT_DEZ_JAN_COGUMELOS_PORTOBELLO_NATAL},
            {MealConstants.PT_DEZ_PEQ_TOFU_MEXIDO_COUVES_BRUXELAS, MealConstants.PT_DEZ_ALM_EMPADAO_LENTILHAS_PURE_DOCE, MealConstants.PT_DEZ_JAN_ESTUFADO_LENTILHAS_PENCA},
            {MealConstants.PT_DEZ_PEQ_CREPE_AVEIA_COMPOTA_PERA, MealConstants.PT_DEZ_ALM_CARIL_INVERNO_COUVE_FLOR, MealConstants.PT_DEZ_JAN_TROUXAS_LOMBARDA_QUINOA},
            {MealConstants.PT_DEZ_PEQ_MUFFIN_BANANA_ESPECIARIAS, MealConstants.PT_DEZ_ALM_MASSA_FORNO_COGUMELOS_TRUFA, MealConstants.PT_DEZ_JAN_SALADA_QUENTE_BRUXELAS},
            {MealConstants.PT_DEZ_PEQ_BATIDO_QUENTE_AVELA_CACAU, MealConstants.PT_DEZ_ALM_COZIDO_MINHOTO_VEGAN, MealConstants.PT_DEZ_JAN_STROGANOFF_INVERNO_SHIITAKE},
            {MealConstants.PT_DEZ_PEQ_PAPA_CENTEIO_MACA_REINETA, MealConstants.PT_DEZ_ALM_LASANHA_COGUMELOS_ALHO_PORRO, MealConstants.PT_DEZ_JAN_QUICHE_ALHO_FRANCES_AVELA},
            {MealConstants.PT_DEZ_PEQ_TORRADA_CREME_AMENDOIM_CACAU, MealConstants.PT_DEZ_ALM_ALMONDEGAS_LENTILHAS_MOLHO, MealConstants.PT_DEZ_JAN_CARIL_GRAO_ESPINAFRE_NOITE},
            {MealConstants.PT_DEZ_PEQ_SCONES_NATAL_PASSAS_NOZ, MealConstants.PT_DEZ_ALM_TARTE_RUSTICA_COUVE_BRUXELAS, MealConstants.PT_DEZ_JAN_MIGAS_BROA_GRELOS_TOFU},
            {MealConstants.PT_DEZ_PEQ_BRUSCHETTA_COZIDO_FORNO, MealConstants.PT_DEZ_ALM_GNOCCHI_CASTANHA_SALVIA, MealConstants.PT_DEZ_JAN_GNOCCHI_ABOBORA_NOZ_MOSCADA},
            {MealConstants.PT_DEZ_PEQ_PAPA_PAINCO_COCO_LARANJA, MealConstants.PT_DEZ_ALM_MIGAS_NATAL_COGUMELOS, MealConstants.PT_DEZ_JAN_BIFE_COUVE_FLOR_AMENDOA},
            {MealConstants.PT_DEZ_PEQ_GRANOLA_INVERNO_IOGURTE, MealConstants.PT_DEZ_ALM_STIR_FRY_TEMPEH_GALEGA, MealConstants.PT_DEZ_JAN_BRUSCHETTA_QUENTE_CASTANHA},
            {MealConstants.PT_DEZ_PEQ_BATIDO_TANGERINA_LINHACA, MealConstants.PT_DEZ_ALM_BURRITO_QUENTE_INVERNO, MealConstants.PT_DEZ_JAN_TEMPEH_GRELHADO_LARANJA_INVERNO},
            {MealConstants.PT_DEZ_PEQ_GALETTE_SARRACENO_REINETA, MealConstants.PT_DEZ_ALM_TACOS_JACKFRUIT_ESPECIARIAS, MealConstants.PT_DEZ_JAN_PATANISCAS_COUVE_ARROZ},
            {MealConstants.PT_DEZ_PEQ_OVO_COCOTE_TRUFA_FORNO, MealConstants.PT_DEZ_ALM_COUSCOUS_NATAL_FRUTOS_SECOS, MealConstants.PT_DEZ_JAN_ESTUFADO_FEIJAO_MANTEIGA_TOMATE},
            {MealConstants.PT_DEZ_PEQ_BARRINHA_AVEIA_FRUTOS_SECOS, MealConstants.PT_DEZ_ALM_FEIJAO_FRADE_GRELOS_TOFU, MealConstants.PT_DEZ_JAN_PASTEL_FORNO_LENTILHAS_NATAL},
            {MealConstants.PT_DEZ_PEQ_TORRADA_REQUEIJAO_TOMILHO, MealConstants.PT_DEZ_ALM_MARMITA_FORNO_RAIZES, MealConstants.PT_DEZ_JAN_CEVADOTTO_LIGEIRO_CEBOLA},
            {MealConstants.PT_DEZ_PEQ_SMOOTHIE_BOWL_ESPINAFRE_PERA, MealConstants.PT_DEZ_ALM_CANELONES_ABOBORA_REQUEIJAO, MealConstants.PT_DEZ_JAN_QUINOA_FORNO_RAIZES_ALECRIM},
            {MealConstants.PT_DEZ_PEQ_PAPA_SARRACENO_MACA_ASSADA, MealConstants.PT_DEZ_ALM_CHILI_VEGAN_INVERNO, MealConstants.PT_DEZ_JAN_TARTE_FOLHADA_BETERRABA_NOZ},
            {MealConstants.PT_DEZ_PEQ_WRAP_QUENTE_AMENDOA_MAÇA, MealConstants.PT_DEZ_ALM_XAREM_INVERNO_PLEUROTUS, MealConstants.PT_DEZ_JAN_MASSA_CREMOSA_CAJU_BRUXELAS},
            {MealConstants.PT_DEZ_PEQ_BOLACHAS_BOLOTA_GINGERBREAD, MealConstants.PT_DEZ_ALM_ESPAGUETE_ALHO_AZEITE_AVELA, MealConstants.PT_DEZ_JAN_BURRITO_BOWL_INVERNO_ARROZ},
            {MealConstants.PT_DEZ_PEQ_TACA_KEFIR_ARANDOS_AVELA, MealConstants.PT_DEZ_ALM_TORTILHA_FORNO_BATATA_ALHO, MealConstants.PT_DEZ_JAN_CREPE_SALGADO_GRAO_PENCA},
            {MealConstants.PT_DEZ_PEQ_PUDIM_LINHACA_KAKI, MealConstants.PT_DEZ_ALM_QUICHE_SEM_MASSA_PENCA, MealConstants.PT_DEZ_JAN_ESPETADAS_TOFU_FUMADO_NABO},
            {MealConstants.PT_DEZ_PEQ_BRUSCHETTA_SHIITAKE_ALECRIM, MealConstants.PT_DEZ_ALM_SEITAN_PIMENTA_PRETA, MealConstants.PT_DEZ_JAN_PAPA_AVEIA_SALGADA_INVERNO},
            {MealConstants.PT_DEZ_PEQ_PANQUECA_CASTANHA_DOCE_ABOBORA, MealConstants.PT_DEZ_ALM_ARROZ_MALANDRO_GRAO_TOMATE, MealConstants.PT_DEZ_JAN_WRAP_FORNO_FEIJAO_ABOBORA},
            {MealConstants.PT_DEZ_PEQ_TACA_IOGURTE_TANGERINA_PINHAO, MealConstants.PT_DEZ_ALM_BATATA_DOCE_FORNO_LENTILHAS, MealConstants.PT_DEZ_JAN_XAREM_NOTURNO_GRELOS}
    };

    private static final Map<String, String> mealVideos = new HashMap<>();
    static {
        mealVideos.put(MealConstants.PT_AVEIA_MIRTILOS, "41Xy3SihQfs");
        mealVideos.put(MealConstants.PT_PANQUECAS_INTEGRAIS, "FcvDYecIcAs");
        mealVideos.put(MealConstants.PT_SMOOTHIE_LINHACA, "DLgJF2jV_mU");
        mealVideos.put(MealConstants.PT_PAPA_SARRACENO, "q_Q-7Mv3Uu0");
        mealVideos.put(MealConstants.PT_PUDIM_CHIA, "o0iN3n-pP7w");
        mealVideos.put(MealConstants.PT_TORRADA_ABACATE, "L6Xo9xGfL-M");
        mealVideos.put(MealConstants.PT_PAINCO_CAJU, "eFf_y4C0E78");
        mealVideos.put(MealConstants.PT_MEXIDO_TOFU_ESPINAFRES, "zH_hI5N_G4M");
        mealVideos.put(MealConstants.PT_SALADA_QUINOA_LEGUMES, "8k2_kGf7oQc");
        mealVideos.put(MealConstants.PT_TACOS_FEIJAO_MILHO, "83uY7n0-nIk");
        mealVideos.put(MealConstants.PT_BROCOLIS_TOFU_GRELHADO, "S-u-8j9f-fI");
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null && getArguments().containsKey("date")) {
            date = getArguments().getString("date");
        } else {
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
            date = formatter.format(new Date());
        }
    }

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_nutrition, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        // Header and Navigation
        view.findViewById(R.id.buttonNutritionCalendar).setOnClickListener(v -> {
            Intent intent = new Intent(v.getContext(), Activity_Calendar.class);
            intent.putExtra("date", date);
            intent.putExtra("fragmentID", 0);
            startActivity(intent);
        });

        // Sliding Hints - Use themed colors
        textSwitcherHints = view.findViewById(R.id.textSwitcherNutritionHints);
        textSwitcherHints.setFactory(() -> {
            TextView textView = new TextView(getContext());
            textView.setGravity(Gravity.START);
            textView.setTextColor(ContextCompat.getColor(requireContext(), R.color.on_nutrition_container));
            textView.setTextSize(16);
            textView.setTypeface(null, android.graphics.Typeface.BOLD);
            return textView;
        });
        textSwitcherHints.setInAnimation(AnimationUtils.loadAnimation(getContext(), android.R.anim.slide_in_left));
        textSwitcherHints.setOutAnimation(AnimationUtils.loadAnimation(getContext(), android.R.anim.slide_out_right));
        startHintsSliding();

        // Meal Suggestions Data Logic
        updateMealSuggestions(view);

        // Setup Meal Cards
        setupMealCard(view.findViewById(R.id.includeBreakfast), todayBreakfast, getString(R.string.nutrition_breakfast_title), getString(R.string.nutrition_breakfast_desc), 0);
        setupMealCard(view.findViewById(R.id.includeLunch), todayLunch, getString(R.string.nutrition_lunch_title), getString(R.string.nutrition_lunch_desc), 1);
        setupMealCard(view.findViewById(R.id.includeDinner), todayDinner, getString(R.string.nutrition_dinner_title), getString(R.string.nutrition_dinner_desc), 2);

        // Summary Clicks
        View.OnClickListener summaryClickListener = v -> showRecipe(((TextView) v).getText().toString());
        view.findViewById(R.id.textBreakfastSuggestion).setOnClickListener(summaryClickListener);
        view.findViewById(R.id.textLunchSuggestion).setOnClickListener(summaryClickListener);
        view.findViewById(R.id.textDinnerSuggestion).setOnClickListener(summaryClickListener);
    }

    private void setupMealCard(View cardContainer, String mealName, String typeLabel, String description, int type) {
        TextView textType = cardContainer.findViewById(R.id.textMealType);
        TextView textTitle = cardContainer.findViewById(R.id.textMealTitle);
        TextView textDesc = cardContainer.findViewById(R.id.textMealDescription);
        Button buttonRecipe = cardContainer.findViewById(R.id.buttonViewRecipe);
        ImageView buttonPlay = cardContainer.findViewById(R.id.buttonPlayVideo);
        YouTubePlayerView playerView = cardContainer.findViewById(R.id.youtube_player);

        textType.setText(typeLabel);
        textTitle.setText(mealName);
        textDesc.setText(description);

        buttonRecipe.setOnClickListener(v -> showRecipe(mealName));
        
        getLifecycle().addObserver(playerView);
        playerView.initialize(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                if (type == 0) breakfastPlayer = youTubePlayer;
                else if (type == 1) lunchPlayer = youTubePlayer;
                else if (type == 2) dinnerPlayer = youTubePlayer;
            }
        });

        buttonPlay.setOnClickListener(v -> {
            YouTubePlayer player = (type == 0) ? breakfastPlayer : (type == 1) ? lunchPlayer : dinnerPlayer;
            playInternalVideo(mealName, player, playerView, cardContainer);
        });
    }

    private void playInternalVideo(String mealName, YouTubePlayer playerObj, YouTubePlayerView playerView, View container) {
        if (!isNetworkAvailable()) {
            Toast.makeText(getContext(), "Sem ligação à internet.", Toast.LENGTH_SHORT).show();
            return;
        }

        String videoId = mealVideos.get(mealName);
        if (videoId != null && playerObj != null) {
            playerView.setVisibility(View.VISIBLE);
            container.findViewById(R.id.imagePlaceholder).setVisibility(View.GONE);
            container.findViewById(R.id.overlay).setVisibility(View.GONE);
            container.findViewById(R.id.layoutText).setVisibility(View.GONE);
            container.findViewById(R.id.buttonPlayVideo).setVisibility(View.GONE);
            playerObj.loadVideo(videoId, 0f);
        } else {
            Toast.makeText(getContext(), "Vídeo brevemente disponível.", Toast.LENGTH_SHORT).show();
        }
    }

    private void updateMealSuggestions(View view) {
        try {
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
            Date dateObj = formatter.parse(date);
            if (dateObj != null) {
                Calendar cal = Calendar.getInstance();
                cal.setTime(dateObj);
                int dayOfMonth = cal.get(Calendar.DAY_OF_MONTH);
                int month = cal.get(Calendar.MONTH); // January is 0, ..., May is 4

                String[][] suggestions;
                if (month == Calendar.FEBRUARY) {
                    suggestions = mealSuggestionsPtFeb;
                } else if (month == Calendar.MARCH) {
                    suggestions = mealSuggestionsPtMar;
                } else if (month == Calendar.APRIL) {
                    suggestions = mealSuggestionsPtApr;
                } else if (month == Calendar.MAY) {
                    suggestions = mealSuggestionsPtMay;
                } else {
                    suggestions = mealSuggestionsPtJan;
                }

                int idx = (dayOfMonth - 1) % suggestions.length;

                todayBreakfast = suggestions[idx][0];
                todayLunch = suggestions[idx][1];
                todayDinner = suggestions[idx][2];

                ((TextView) view.findViewById(R.id.textBreakfastSuggestion)).setText(todayBreakfast);
                ((TextView) view.findViewById(R.id.textLunchSuggestion)).setText(todayLunch);
                ((TextView) view.findViewById(R.id.textDinnerSuggestion)).setText(todayDinner);
            }
        } catch (Exception ignored) {}
    }

    private void startHintsSliding() {
        textSwitcherHints.setText(getString(nutritionHints[currentHintIdx]));
        hintRunnable = new Runnable() {
            @Override
            public void run() {
                currentHintIdx = (currentHintIdx + 1) % nutritionHints.length;
                textSwitcherHints.setText(getString(nutritionHints[currentHintIdx]));
                hintHandler.postDelayed(this, 5000);
            }
        };
        hintHandler.postDelayed(hintRunnable, 5000);
    }

    private void showRecipe(String title) {
        if (title == null || title.isEmpty() || title.equals("Loading...")) return;
        DatabaseHelper db = new DatabaseHelper(getContext());
        String htmlContent = db.getRecipeContent(title);
        Intent intent = new Intent(getContext(), Activity_FullContent.class);
        intent.putExtra("title", title);
        intent.putExtra("content", htmlContent != null ? htmlContent : "<h1>Receita em breve!</h1>");
        intent.putExtra("fragmentID", 0); // Nutrition
        startActivity(intent);
    }

    private boolean isNetworkAvailable() {
        ConnectivityManager cm = (ConnectivityManager) requireContext().getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo netInfo = cm.getActiveNetworkInfo();
        return netInfo != null && netInfo.isConnected();
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        if (hintRunnable != null) hintHandler.removeCallbacks(hintRunnable);
    }
}
