# Project-wide Gradle settings.

# Increase timeout to 10 minutes (values are in milliseconds)
systemProp.org.gradle.internal.http.connectionTimeout=600000
systemProp.org.gradle.internal.http.socketTimeout=600000

# Removed explicit SNI flag to allow default JVM behavior
org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true

# AndroidX settings
android.useAndroidX=true
android.nonTransitiveRClass=false
