pluginManagement {
    repositories {
        maven { 
            url 'http://repo.huaweicloud.com/repository/maven/google/' 
            allowInsecureProtocol = true
        }
        maven { 
            url 'http://repo.huaweicloud.com/repository/maven/' 
            allowInsecureProtocol = true
        }
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { 
            url 'http://repo.huaweicloud.com/repository/maven/google/' 
            allowInsecureProtocol = true
        }
        maven { 
            url 'http://repo.huaweicloud.com/repository/maven/'
            allowInsecureProtocol = true
        }
    }
}
rootProject.name = "Newstart"
include ':app'
